// DataGrapher_text.c
// Generated by decompiling DataGrapher.exe
// using Reko decompiler version 0.9.1.0.

#include "DataGrapher_text.h"

// 00411014: void fn00411014(Register Eq_2 edx, Register ui32 ebx, Register Eq_2 esi, Register Eq_2 edi, Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds)
void fn00411014(Eq_2 edx, ui32 ebx, Eq_2 esi, Eq_2 edi, struct Eq_6 * es, struct Eq_7 * ds)
{
	ui32 eax_10 = globals->t41B004 ^ fp - 0x04;
	globals->dw41B580 = 0x00;
	globals->dw41B034 |= 0x01;
	if (fn0041106E(0x0A) != 0x00)
	{
		byte bLoc30_342;
		__cpuid(0x00, 0x00, &0x00, &ebx, &0x00, &edx);
		ui32 dwLoc0C_334 = 0x00;
		ui32 edx_53 = ebx ^ 1970169159 | edx ^ 0x49656E69;
		if ((edx_53 | 1818588270) == 0x00)
			bLoc30_342 = 0x01;
		else
			bLoc30_342 = 0x00;
		__cpuid(0x01, 0x00, &0x01, &ebx, &0x00, &(edx_53 | 1818588270));
		if ((word32) bLoc30_342 != 0x00 && (0x00 == 0x000106C0 || (0x00 == 0x00020660 || (0x00 == 0x00020670 || (0x00 == 0x00030650 || (0x00 == 0x00030660 || false))))))
			globals->dw41B584 |= 0x01;
		if (false)
		{
			__cpuid(0x07, 0x00, &0x07, &ebx, &0x00, &0x00);
			dwLoc0C_334 = ebx;
			if ((ebx & 0x0200) != 0x00)
				globals->dw41B584 |= 0x02;
		}
		globals->dw41B580 = 0x01;
		globals->dw41B034 |= 0x02;
		edx.u0 = 0x00;
		if (0x00 != 0x00)
		{
			globals->dw41B580 = 0x02;
			globals->dw41B034 |= 0x04;
			edx.u0 = 0x00;
			if (0x00 != 0x00 && 0x00 != 0x00)
			{
				word64 edx_eax_190 = __xgetbv(0x00);
				ui32 eax_191 = (word32) edx_eax_190;
				ui32 edx_193 = SLICE(edx_eax_190, word32, 32);
				edx = eax_191 & 0x06;
				if ((eax_191 & 0x06) == 0x06 && (edx_193 & 0x00) == 0x00)
				{
					globals->dw41B580 = 0x03;
					globals->dw41B034 |= 0x08;
					edx.u0 = 0x08;
					if ((dwLoc0C_334 & 0x20) != 0x00)
					{
						globals->dw41B580 = 0x05;
						globals->dw41B034 |= 0x20;
						edx.u0 = 0x08;
						if ((dwLoc0C_334 & 0xD0030000) == 0xD0030000)
						{
							edx = edx_193 & 0x00;
							if ((eax_191 & 0xE0) == 0xE0 && (edx_193 & 0x00) == 0x00)
							{
								globals->dw41B580 = 0x06;
								globals->dw41B034 |= 0x40;
							}
						}
					}
				}
			}
		}
	}
	word32 edx_406;
	fn00411249(eax_10 ^ fp - 0x04, edx, esi, fp - 0x04, 0x0A, edi, es, ds, esi, out edx_406);
}

// 00411028: void fn00411028()
void fn00411028()
{
	cexit();
}

// 00411046: Register word32 fn00411046()
word32 fn00411046()
{
	return globals->dw41B51C;
}

// 0041105A: void fn0041105A()
void fn0041105A()
{
	SDL2.dll!SDL_RenderClear();
}

// 00411064: Register word32 fn00411064(Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Register word128 xmm0)
word32 fn00411064(struct Eq_6 * es, struct Eq_7 * ds, word128 xmm0)
{
	return fn00415920(es, ds, xmm0);
}

// 0041106E: Register Eq_251 fn0041106E(Stack Eq_2 tArg04)
Eq_251 fn0041106E(Eq_2 tArg04)
{
	return IsProcessorFeaturePresent(tArg04);
}

// 00411078: void fn00411078()
void fn00411078()
{
	_vcrt_GetModuleFileNameW();
}

// 0041107D: Register int32 fn0041107D(Stack (ptr32 Eq_259) ptrArg04, Stack (ptr32 Eq_260) ptrArg08)
int32 fn0041107D(PVFV * ptrArg04, PVFV * ptrArg08)
{
	return _initterm_e(ptrArg04, ptrArg08);
}

// 0041108C: void fn0041108C()
void fn0041108C()
{
	SDL2.dll!SDL_GetWindowID();
}

// 0041109B: void fn0041109B()
void fn0041109B()
{
}

// 004110AF: void fn004110AF(Stack Eq_268 bArg04)
void fn004110AF(Eq_268 bArg04)
{
	if (fn004110FF() != 0x00 && (word32) bArg04 == 0x00)
		globals->dw41B52C = 0x00;
}

// 004110C8: void fn004110C8()
void fn004110C8()
{
	register_thread_local_exe_atexit_callback();
}

// 004110D2: Register word32 fn004110D2(Stack (ptr32 Eq_283) dwArg04)
word32 fn004110D2(struct _EXCEPTION_POINTERS * dwArg04)
{
	return fn00413370(dwArg04);
}

// 004110EB: void fn004110EB()
void fn004110EB()
{
	SDL2.dll!SDL_CreateRenderer();
}

// 004110FF: Register word32 fn004110FF()
word32 fn004110FF()
{
	word32 dwLoc08_23;
	if (globals->dw41B038 != 0x00)
		dwLoc08_23 = 0x01;
	else
		dwLoc08_23 = 0x00;
	return dwLoc08_23;
}

// 0041110E: void fn0041110E()
void fn0041110E()
{
}

// 00411122: void fn00411122(Stack (ptr32 void) ptrArg04, Stack int32 dwArg08, Stack Eq_2 tArg0C)
void fn00411122(void * ptrArg04, int32 dwArg08, Eq_2 tArg0C)
{
	memset(ptrArg04, dwArg08, tArg0C);
}

// 00411127: void fn00411127()
void fn00411127()
{
	SDL2.dll!SDL_RenderPresent();
}

// 00411140: void fn00411140()
void fn00411140()
{
	SDL2.dll!SDL_Init();
}

// 0041114A: void fn0041114A()
void fn0041114A()
{
	fn00414690();
}

// 0041114F: void fn0041114F()
void fn0041114F()
{
	_vcrt_GetModuleHandleW();
}

// 00411154: Register byte fn00411154(Register Eq_2 edx, Register ui32 ebx, Register Eq_2 esi, Register Eq_2 edi, Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Stack word32 dwArg04)
byte fn00411154(Eq_2 edx, ui32 ebx, Eq_2 esi, Eq_2 edi, struct Eq_6 * es, struct Eq_7 * ds, word32 dwArg04)
{
	return (byte) (uint32) (uint8) fn00413BB0(edx, ebx, esi, edi, es, ds, dwArg04);
}

// 00411172: Register (ptr32 Eq_337) fn00411172(Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Register word128 xmm0, Stack (ptr32 Eq_337) dwArg04, Register out Eq_342 xmm0Out)
struct Eq_337 * fn00411172(struct Eq_6 * es, struct Eq_7 * ds, word128 xmm0, struct Eq_337 * dwArg04, union Eq_342 & xmm0Out)
{
	word32 * edi_19 = fp - 0x010C;
	word32 ecx_20;
	for (ecx_20 = 66; ecx_20 != 0x00; --ecx_20)
	{
		*edi_19 = 0xCCCCCCCC;
		++edi_19;
	}
	fn00411285(&globals->b41D02F);
	word16 ax_40 = (word16) (int32) ((int64) (word32) dwArg04->w0006 / 0x0A);
	word16 ax_50 = (word16) (int32) ((int64) (word32) dwArg04->w0006 / 100);
	word16 ax_60 = (word16) (int32) ((int64) (word32) dwArg04->w0008 / 0x0A);
	word16 ax_72 = (word16) (int32) ((int64) (word32) dwArg04->w0008 / 100);
	fn00411276();
	Eq_397 v18_90 = (real32) (word32) dwArg04->w0006;
	real128 xmm0_353 = DPB(xmm0, v18_90, 0);
	Eq_397 rLoc0C_413;
	for (rLoc0C_413 = v18_90; rLoc0C_413 >= globals->t418B40; rLoc0C_413 -= xmm0_353)
	{
		fn00411212();
		xmm0_353 = DPB(xmm0_353, (real32) (word32) ax_50, 0);
	}
	int32 dwLoc18_415 = 0x00;
	while (dwLoc18_415 <= (word32) dwArg04->w0008)
	{
		fn00411212();
		dwLoc18_415 = (word32) ax_72 + dwLoc18_415;
	}
	fn00411276();
	Eq_397 v27_125 = (real32) (word32) dwArg04->w0006;
	real128 xmm0_127 = DPB(xmm0_353, v27_125, 0);
	Eq_397 rLoc0C_424 = v27_125;
	while (true)
	{
		Eq_342 xmm0_132 = DPB(xmm0_127, rLoc0C_424, 0);
		if (rLoc0C_424 < globals->t418B40)
			break;
		fn00411212();
		xmm0_127 = DPB(xmm0_127, (real32) (word32) ax_40, 0);
		rLoc0C_424 -= xmm0_127;
	}
	int32 dwLoc18_426 = 0x00;
	while (dwLoc18_426 <= (word32) dwArg04->w0008)
	{
		fn00411212();
		dwLoc18_426 = (word32) ax_60 + dwLoc18_426;
	}
	fn00411276();
	fn00411212();
	fn00411212();
	fn00411276();
	fn004113E3();
	dwArg04->b0004 = 0x00;
	fn0041128F(es, ds, dwLoc08);
	xmm0Out = xmm0_132;
	return dwArg04;
}

// 00411177: Register byte fn00411177()
byte fn00411177()
{
	return 0x01;
}

// 0041117C: void fn0041117C(Stack (ptr32 char) ptrArg04, Stack Eq_495 tArg08, Stack (ptr32 char) ptrArg0C)
void fn0041117C(char * ptrArg04, Eq_495 tArg08, char * ptrArg0C)
{
	strcat_s(ptrArg04, tArg08, ptrArg0C);
}

// 0041119A: Register Eq_502 fn0041119A(Stack (ptr32 wchar_t) ptrArg04, Stack Eq_2 tArg08, Stack (ptr32 wchar_t) ptrArg0C, Stack (ptr32 wchar_t) ptrArg10, Stack (ptr32 wchar_t) ptrArg14, Stack (ptr32 wchar_t) ptrArg18)
Eq_502 fn0041119A(wchar_t * ptrArg04, Eq_2 tArg08, wchar_t * ptrArg0C, wchar_t * ptrArg10, wchar_t * ptrArg14, wchar_t * ptrArg18)
{
	return _wmakepath_s(ptrArg04, tArg08, ptrArg0C, ptrArg10, ptrArg14, ptrArg18);
}

// 004111A9: Register word32 fn004111A9()
word32 fn004111A9()
{
	return globals->dw41B520;
}

// 004111CC: void fn004111CC()
void fn004111CC()
{
	SDL2.dll!SDL_SetMainReady();
}

// 004111D6: void fn004111D6()
void fn004111D6()
{
	SDL2.dll!SDL_Quit();
}

// 004111E0: Register ptr32 fn004111E0()
ptr32 fn004111E0()
{
	return 4306328;
}

// 004111EA: void fn004111EA(Register Eq_2 edx, Register Eq_2 ebx, Register Eq_2 esi, Register Eq_2 edi, Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Stack Eq_2 dwArg04, Stack (ptr32 char) dwArg08)
void fn004111EA(Eq_2 edx, Eq_2 ebx, Eq_2 esi, Eq_2 edi, struct Eq_6 * es, struct Eq_7 * ds, Eq_2 dwArg04, char * dwArg08)
{
	ui32 eax_10 = globals->t41B004 ^ fp - 0x04;
	word32 edi_23 = globals->dw41B01C;
	if (edi_23 != ~0x00)
	{
		Eq_2 eax_41;
		if (*dwArg08 != 0x00 && fn00412ED0(dwArg08, out edx) <= 0x03D3)
		{
			fn0041134D(fp - 0x0408, 0x0400, "Stack around the variable '");
			fn0041117C(fp - 0x0408, 0x0400, dwArg08);
			fn0041117C(fp - 0x0408, 0x0400, "' was corrupted.");
			eax_41 = fp - 0x0408;
		}
		else
			eax_41.u0 = 0x004190A0;
		edx = fn00412EF0(edx, es, ds, dwArg04, edi_23, 0x02, eax_41);
	}
	word32 edx_188;
	fn00411249(eax_10 ^ fp - 0x04, edx, ebx, fp - 0x04, esi, edi, es, ds, ebx, out edx_188);
}

// 004111EF: void fn004111EF()
void fn004111EF()
{
}

// 00411203: void fn00411203()
void fn00411203()
{
	SDL2.dll!SDL_PollEvent();
}

// 00411212: void fn00411212()
void fn00411212()
{
	SDL2.dll!SDL_RenderDrawLine();
}

// 00411217: Register byte fn00411217(Stack Eq_268 dwArg04)
byte fn00411217(Eq_268 dwArg04)
{
	word32 eax_151;
	ptr32 eax_15 = fs->ptr0000;
	fs->ptr0000 = fp - 0x14;
	uint32 eax_47 = (uint32) (uint8) fn00413920(&globals->t400000);
	word24 eax_24_8_152 = SLICE(eax_47, word24, 8);
	if ((word32) (byte) eax_47 == 0x00)
		eax_151 = SEQ(eax_24_8_152, 0x00);
	else
	{
		struct Eq_635 * eax_70 = fn00413870(&globals->t400000, dwArg04 - 0x00400000);
		word24 eax_24_8_154 = SLICE(eax_70, word24, 8);
		if (eax_70 == null)
			eax_151 = SEQ(eax_24_8_154, 0x00);
		else
		{
			word24 eax_24_8_156 = SLICE(eax_70, word24, 8);
			if ((eax_70->dw0024 & 0x80000000) != 0x00)
				eax_151 = SEQ(eax_24_8_156, 0x00);
			else
				eax_151 = SEQ(eax_24_8_156, 0x01);
		}
	}
	fs->ptr0000 = eax_15;
	return (byte) eax_151;
}

// 00411221: void fn00411221(Stack (ptr32 Eq_668) ptrArg04, Stack (ptr32 Eq_260) ptrArg08)
void fn00411221(PVFV * ptrArg04, PVFV * ptrArg08)
{
	_initterm(ptrArg04, ptrArg08);
}

// 00411230: Register byte fn00411230()
byte fn00411230()
{
	uip32 eax_70;
	Eq_2 eax_11 = GetModuleHandleW(null);
	word24 eax_24_8_71 = SLICE(eax_11, word24, 8);
	if (eax_11 == 0x00)
		eax_70 = SEQ(eax_24_8_71, 0x00);
	else
	{
		word24 eax_24_8_73 = SLICE(eax_11, word24, 8);
		if ((word32) *eax_11 != 23117)
			eax_70 = SEQ(eax_24_8_73, 0x00);
		else
		{
			word32 eax_22 = eax_11 + Mem13[eax_11 + 0x3C:word32];
			word24 eax_24_8_75 = SLICE(eax_22, word24, 8);
			if (eax_22->unused != 0x4550)
				eax_70 = SEQ(eax_24_8_75, 0x00);
			else
			{
				word32 eax_28 = (word32) eax_22->dw0018;
				word24 eax_24_8_77 = SLICE(eax_28, word24, 8);
				if (eax_28 != 0x010B)
					eax_70 = SEQ(eax_24_8_77, 0x00);
				else if (eax_22->t0074 <= 0x0E)
					eax_70 = SEQ(eax_24_8_77, 0x00);
				else if (eax_22->dw00E8 == 0x00)
					eax_70 = 0x00;
				else
					eax_70 = 0x01;
			}
		}
	}
	return (byte) eax_70;
}

// 00411249: Register word32 fn00411249(Register Eq_10 ecx, Register Eq_2 edx, Register Eq_2 ebx, Register ptr32 ebp, Register Eq_2 esi, Register Eq_2 edi, Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Stack Eq_2 dwArg00, Register out Eq_2 edxOut)
word32 fn00411249(Eq_10 ecx, Eq_2 edx, Eq_2 ebx, ptr32 ebp, Eq_2 esi, Eq_2 edi, struct Eq_6 * es, struct Eq_7 * ds, Eq_2 dwArg00, union Eq_2 & edxOut)
{
	if (ecx != globals->t41B004)
	{
		Eq_2 edx_21;
		word32 eax_19 = fn004133B0(ecx, edx, ebx, ebp, esi, edi, es, ds, dwArg00, out edx_21);
		edxOut = edx_21;
		return eax_19;
	}
	else
	{
		edxOut = edx;
		return eax;
	}
}

// 00411276: void fn00411276()
void fn00411276()
{
	SDL2.dll!SDL_SetRenderDrawColor();
}

// 0041127B: void fn0041127B()
void fn0041127B()
{
	fn00411122(fp - 0x4C, 0x00, 0x44);
	GetStartupInfoW(fp - 0x4C);
}

// 00411285: void fn00411285(Register (ptr32 byte) ecx)
void fn00411285(byte * ecx)
{
	fn00412540(ecx);
}

// 0041128F: void fn0041128F(Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Stack Eq_2 dwArg00)
void fn0041128F(struct Eq_6 * es, struct Eq_7 * ds, Eq_2 dwArg00)
{
	fn00412500(es, ds, dwArg00);
}

// 004112B2: Register ptr32 fn004112B2()
ptr32 fn004112B2()
{
	return 4306316;
}

// 004112B7: void fn004112B7(Register Eq_2 ecx, Register Eq_2 edx, Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Stack Eq_2 dwArg00)
void fn004112B7(Eq_2 ecx, Eq_2 edx, struct Eq_6 * es, struct Eq_7 * ds, Eq_2 dwArg00)
{
	fn00412490(ecx, edx, es, ds, dwArg00);
}

// 004112BC: void fn004112BC()
void fn004112BC()
{
	SDL2.dll!SDL_CreateWindow();
}

// 004112C1: Register Eq_2 Win32CrtStartup()
Eq_2 Win32CrtStartup()
{
	return fn00412780(ebx, esi, edi, es, ds, xmm0);
}

// 004112C6: void fn004112C6(Stack Eq_823 bArg08)
void fn004112C6(Eq_823 bArg08)
{
	if ((word32) globals->b41B530 == 0x00 || (word32) bArg08 == 0x00)
	{
		fn0041109B();
		fn0041110E();
	}
}

// 004112DA: void fn004112DA(Stack int32 dwArg04)
void fn004112DA(int32 dwArg04)
{
	exit(dwArg04);
}

// 004112E9: Register Eq_502 fn004112E9(Stack (ptr32 wchar_t) ptrArg04, Stack (ptr32 wchar_t) ptrArg08, Stack Eq_2 tArg0C, Stack (ptr32 wchar_t) ptrArg10, Stack Eq_2 tArg14, Stack (ptr32 wchar_t) ptrArg18, Stack Eq_2 tArg1C, Stack (ptr32 wchar_t) ptrArg20, Stack Eq_2 tArg24)
Eq_502 fn004112E9(wchar_t * ptrArg04, wchar_t * ptrArg08, Eq_2 tArg0C, wchar_t * ptrArg10, Eq_2 tArg14, wchar_t * ptrArg18, Eq_2 tArg1C, wchar_t * ptrArg20, Eq_2 tArg24)
{
	return _wsplitpath_s(ptrArg04, ptrArg08, tArg0C, ptrArg10, tArg14, ptrArg18, tArg1C, ptrArg20, tArg24);
}

// 004112EE: void fn004112EE(Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Stack Eq_2 dwArg04, Stack uint32 dwArg08)
void fn004112EE(struct Eq_6 * es, struct Eq_7 * ds, Eq_2 dwArg04, uint32 dwArg08)
{
	fn00412CF0(es, ds, dwArg04, dwArg08);
}

// 00411307: Register word32 fn00411307(Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Register word128 xmm0, Register out Eq_2 ebxOut)
word32 fn00411307(struct Eq_6 * es, struct Eq_7 * ds, word128 xmm0, union Eq_2 & ebxOut)
{
	word32 * edi_19 = fp - 0x01AC;
	word32 ecx_20;
	for (ecx_20 = 0x6A; ecx_20 != 0x00; --ecx_20)
	{
		*edi_19 = 0xCCCCCCCC;
		++edi_19;
	}
	word32 eax_293;
	ui32 eax_26 = globals->t41B004 ^ fp - 0x04;
	fn00411285(&globals->b41D049);
	struct Eq_897 * eax_45 = malloc(0x18);
	fn0041128F(es, ds, 0x18);
	eax_45->w0006 = 400;
	eax_45->w0008 = 500;
	eax_45->dw0000 = (word32) eax_45->w0008 + 0x14;
	uint32 eax_75 = eax_45->dw0000;
	Eq_2 ecx_86 = -(uint32) (uint8) OVERFLOW(eax_75 * 0x08) | (word32) (eax_75 * 0x08);
	struct Eq_897 * eax_90 = malloc(ecx_86);
	fn0041128F(es, ds, ecx_86);
	eax_45->ptr000C = eax_90;
	eax_45->b0004 = 0x00;
	eax_45->b0005 = 0x00;
	eax_45->w0014 = 0x03FF;
	fn00411140();
	fn004112BC();
	fn004110EB();
	struct Eq_897 * eax_142 = malloc(0x04);
	fn0041128F(es, ds, 0x04);
	fn0041108C();
	eax_142->dw0000 = 700;
	Eq_2 eax_172 = CreateFileW(&globals->t418B44, 0x80000000, 0x00, null, 0x03, 0x00, 0x00);
	fn0041128F(es, ds, 0x00);
	eax_45->t0010 = eax_172;
	byte bLoc31_547 = 0x00;
	Eq_2 edx_124 = 4295472;
	ptr32 esp_173 = fp - 440;
	if (eax_45->t0010 == ~0x00)
		eax_293 = 0x01;
	else
	{
		GetCommState(eax_45->t0010, fp - 200);
		fn0041128F(es, ds, fp - 200);
		SetCommState(eax_45->t0010, fp - 200);
		fn0041128F(es, ds, fp - 200);
		edx_124 = eax_45->t0010;
		Eq_251 eax_249 = SetCommTimeouts(edx_124, fp - 228);
		fn0041128F(es, ds, fp - 228);
		esp_173 = fp - 440;
		if (eax_249 == 0x00)
			eax_293 = 0x04;
		else
		{
			while ((word32) bLoc31_547 == 0x00)
			{
				while (true)
				{
					ptr32 * esp_309 = esp_173 - 0x04;
					*esp_309 = fp - 116;
					fn00411203();
					if (fp == 116)
						break;
					if (dwLoc74 == 0x0100)
						bLoc31_547 = 0x01;
				}
				if ((word32) eax_45->b0004 != 0x00)
				{
					*esp_309 = 0xFF;
					*(esp_309 - 0x04) = 0xFF;
					*(esp_309 - 0x08) = 0xFF;
					*(esp_309 - 0x0C) = 0xFF;
					*(esp_309 - 0x0010) = 700;
					fn00411276();
					*esp_309 = 700;
					fn0041105A();
					*esp_309 = 700;
					*(esp_309 - 0x04) = (struct Eq_897 **) eax_45;
					edx_124 = fn00411172(es, ds, xmm0, *(esp_309 - 0x04), out xmm0);
					*esp_309 = 700;
					fn00411127();
				}
				if ((word32) eax_45->b0005 == 0x00)
				{
					struct Eq_897 ** esp_377 = esp_173 - 0x04;
					*esp_377 = (struct Eq_897 **) eax_45;
					*(esp_377 - 0x04) = 0x00;
					*(esp_377 - 0x08) = 0x004110F5;
					struct Eq_1290 * esp_389;
					beginthread();
					fn0041128F(es, ds, esp_389->t0008);
					eax_45->b0005 = 0x01;
					esp_173 = (char *) &esp_389->t0008 + 0x04;
				}
			}
			while ((word32) eax_45->b0005 != 0x00)
			{
				union Eq_2 * esp_297 = esp_173 - 0x04;
				*esp_297 = 0x0A;
				Sleep(*esp_297);
				fn0041128F(es, ds, *esp_297);
			}
			fn004111D6();
			union Eq_2 * esp_277 = esp_173 - 0x04;
			*esp_277 = (union Eq_2 *) eax_45->t0010;
			CloseHandle(*esp_277);
			fn0041128F(es, ds, *esp_277);
			esp_173 = (char *) esp_277 + 0x04;
			eax_293 = 0x00;
		}
	}
	struct Eq_1074 * esp_428 = esp_173 - 0x04;
	esp_428->t0000 = edx_124;
	*(esp_428 - 0x04) = eax_293;
	fn004112B7(fp - 0x04, 4267656, es, ds, esp_428->tFFFFFFF8);
	Eq_2 ebx_464 = esp_428->t000C;
	word32 edx_681;
	word32 eax_470 = fn00411249(eax_26 ^ fp - 0x04, esp_428->t0000, ebx_464, fp - 0x04, esp_428->t0008, esp_428->t0004, es, ds, esp_428->t000C, out edx_681);
	fn0041128F(es, ds, esp_428->t01B4);
	ebxOut = ebx_464;
	return eax_470;
}

// 00411348: Register word32 fn00411348()
word32 fn00411348()
{
	return fn004140C0();
}

// 0041134D: void fn0041134D(Stack (ptr32 char) ptrArg04, Stack Eq_495 tArg08, Stack (ptr32 char) ptrArg0C)
void fn0041134D(char * ptrArg04, Eq_495 tArg08, char * ptrArg0C)
{
	strcpy_s(ptrArg04, tArg08, ptrArg0C);
}

// 00411357: void fn00411357()
void fn00411357()
{
	_vcrt_LoadLibraryExW();
}

// 0041135C: Register byte fn0041135C()
byte fn0041135C()
{
	return 0x01;
}

// 00411361: void fn00411361(Stack word32 dwArg04)
void fn00411361(word32 dwArg04)
{
	if (fn0041106E(0x17) == 0x00)
	{
		byte bLoc05_151;
		fn0041114A();
		fn00411122(fp - 0x0330, 0x00, 0x02CC);
		fn00411122(fp - 100, 0x00, 0x50);
		if (IsDebuggerPresent() == 0x01)
			bLoc05_151 = 0x01;
		else
			bLoc05_151 = 0x00;
		SetUnhandledExceptionFilter(null);
		if (UnhandledExceptionFilter(fp - 0x14) == 0x00 && (word32) bLoc05_151 == 0x00)
			fn0041114A();
	}
	else
		__fastfail(dwArg04);
}

// 004113B1: void fn004113B1()
void fn004113B1()
{
	get_narrow_winmain_command_line();
}

// 004113CF: Register Eq_502 fn004113CF(Stack (ptr32 wchar_t) ptrArg04, Stack Eq_495 tArg08, Stack (ptr32 wchar_t) ptrArg0C)
Eq_502 fn004113CF(wchar_t * ptrArg04, Eq_495 tArg08, wchar_t * ptrArg0C)
{
	return wcscpy_s(ptrArg04, tArg08, ptrArg0C);
}

// 004113E3: void fn004113E3()
void fn004113E3()
{
	SDL2.dll!SDL_RenderDrawLines();
}

// 004113F7: Register word32 fn004113F7()
word32 fn004113F7()
{
	return fs->dw0018;
}

// 004113FC: Register byte fn004113FC()
byte fn004113FC()
{
	word32 eax_55;
	word32 eax_10 = fn004110FF();
	word24 eax_24_8_56 = SLICE(eax_10, word24, 8);
	if (eax_10 == 0x00)
		eax_55 = SEQ(eax_24_8_56, 0x00);
	else
	{
		word32 eax_20 = fn004113F7()->dw0004;
		do
		{
			__lock();
			word32 eax_27;
			__cmpxchg(globals->dw41B52C, eax_20, 0x00, out eax_27);
			word24 eax_24_8_60 = SLICE(eax_27, word24, 8);
			if (eax_27 == 0x00)
			{
				eax_55 = SEQ(eax_24_8_60, 0x00);
				return (byte) eax_55;
			}
			word24 eax_24_8_58 = SLICE(eax_20, word24, 8);
		} while (eax_20 != eax_27);
		eax_55 = SEQ(eax_24_8_58, 0x01);
	}
	return (byte) eax_55;
}

// 00411401: Register word32 fn00411401(Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Stack ui32 dwArg04, Stack (ptr32 word16) dwArg08, Stack (ptr32 ui32) dwArg10, Stack ptr32 dwArg14, Stack word32 dwArg18)
word32 fn00411401(struct Eq_6 * es, struct Eq_7 * ds, ui32 dwArg04, word16 * dwArg08, ui32 * dwArg10, ptr32 dwArg14, word32 dwArg18)
{
	*dwArg10 = 0x00;
	*dwArg08 = 0x00;
	Eq_1449 eax_33 = VirtualQuery(dwArg04 - 0x01, fp - 0x50, 0x1C);
	if (eax_33 == 0x00)
		return edi;
	fn00411078();
	if (eax_33 == 0x00 || dwLoc4C->w0000 != 23117)
		return edi;
	int32 ecx_56 = dwLoc4C->dw003C;
	if (ecx_56 <= 0x00)
		return edi;
	struct Eq_1481 * ecx_59 = dwLoc4C + ecx_56 / 0x0040;
	if (ecx_59->dw0000 != 0x4550)
		return edi;
	word32 edx_62 = (word32) ecx_59->w0014;
	Eq_2 esi_63 = dwArg04 - 0x01 - dwLoc4C;
	Eq_2 edi_64 = (word32) ecx_59->w0006;
	Eq_2 edx_142 = edx_62 + 0x20;
	Eq_2 ebx_145 = 0x00;
	Eq_2 eax_67 = 0x00;
	if (edi_64 != 0x00)
	{
		struct Eq_1511 * ecx_73 = &(ecx_59 + (edx_62 + 0x20) / 22)->dw0000 + 0x01;
		do
		{
			edx_142 = ecx_73->dw0000;
			if (esi_63 >= edx_142)
			{
				ebx_145 = esi_63 - edx_142;
				if (esi_63 < ecx_73->dw0000)
					goto l00414E4F;
			}
			eax_67 = (word32) eax_67 + 0x01;
			++ecx_73;
		} while (eax_67 < edi_64);
	}
	if (eax_67 == edi_64)
		return edi;
l00414E4F:
	Eq_2 eax_109;
	up32 eax_98 = (word32) eax_67 + 0x01;
	if (globals->b41B57D == 0x00)
	{
		if (globals->t41B578 != 0x00)
			return edi;
		eax_109 = fn00414810(edx_142, ebx_145, esi_63, edi_64, es, ds, out ebx_145);
		globals->t41B578 = eax_109;
		if (eax_109 == 0x00)
			return edi;
		globals->b41B57D = 0x01;
	}
	else
		eax_109 = globals->t41B578;
	Eq_1562 eax_178 = GetProcAddress(eax_109, &globals->t41952C);
	if (eax_178 == null)
		return edi;
	fn004111EF();
	if (eax_178() == 0x00)
		return edi;
	<anonymous> * esi_246 = **dwLoc1C;
	fn004111EF();
	ptr32 esp_249;
	word32 eax_250;
	word32 edx_252;
	esi_246();
	if (eax_250 == 20091201)
	{
		<anonymous> * esi_259 = *((char *) *dwLoc1C + 0x001C);
		*(esp_249 - 0x04) = fp - 0x24;
		*(esp_249 - 0x08) = 0x00419540;
		*(esp_249 - 0x0C) = 0x00;
		fn004111EF();
		ptr32 esp_269;
		word32 eax_270;
		word32 edx_272;
		esi_259();
		if (eax_270 != 0x00)
		{
			*(esp_269 - 0x04) = 0x00;
			*(esp_269 - 0x08) = 0x00;
			*(esp_269 - 0x0C) = 0x00;
			<anonymous> * esi_286 = *((char *) *dwLoc24 + 0x0020);
			*(esp_269 - 0x0010) = fp - 0x18;
			*(esp_269 - 0x0014) = (union Eq_2 *) ebx_145;
			*(esp_269 - 0x0018) = eax_98;
			fn004111EF();
			ptr32 esp_297;
			word32 eax_298;
			word32 edx_300;
			esi_286();
			if (eax_298 != 0x00)
			{
				<anonymous> * esi_308 = *((char *) *dwLoc18 + 0x0068);
				*(esp_297 - 0x04) = fp - 0x0C;
				fn004111EF();
				word32 eax_315;
				word32 edx_317;
				esi_308();
				if ((byte) eax_315 != 0x00 && 0x00 != 0x00)
				{
					Eq_1734 ecx_438;
					<anonymous> * esi_329 = *((char *) null + 0x08);
					fn004111EF();
					word32 eax_333;
					word32 edx_335;
					ptr32 esp_332;
					esi_329();
					if (eax_333 != 0x00)
					{
						do
						{
							word32 * esp_345 = esp_332 - 0x04;
							*esp_345 = 0x00;
							<anonymous> * esi_348 = *((char *) null + 0x0C);
							*(esp_345 - 0x04) = fp - 0x14;
							*(esp_345 - 0x08) = fp - 44;
							*(esp_345 - 0x0C) = fp - 0x08;
							*(esp_345 - 0x0010) = fp - 0x20;
							*(esp_345 - 0x0014) = 0x00;
							fn004111EF();
							ptr32 esp_373;
							word32 eax_374;
							word32 edx_376;
							esi_348();
							if ((byte) eax_374 == 0x00)
								goto l00414FF9;
							if ((word32) wLoc08 == eax_98 && (dwLoc20 <= ebx_145 && ebx_145 < (word32) dwLoc20 + dwLoc2C))
							{
								if (dwLoc14 == 0x00 || dwLoc14 >= 0x1FFFFFFF)
									goto l00414FF9;
								Eq_2 eax_400 = GetProcessHeap();
								*(esp_373 - 0x04) = dwLoc14 << 0x03;
								*(esp_373 - 0x08) = 0x00;
								*(esp_373 - 0x0C) = (union Eq_2 *) eax_400;
								Eq_1734 eax_407 = HeapAlloc(*(esp_373 - 0x0C), *(esp_373 - 0x08), *(esp_373 - 0x04));
								if (eax_407 == 0x00)
									goto l00414FF9;
								*(esp_373 - 0x04) = (union Eq_1734 *) eax_407;
								*(esp_373 - 0x08) = fp - 0x14;
								struct Eq_1737 * ecx_419 = null;
								*(esp_373 - 0x0C) = 0x00;
								*(esp_373 - 0x0010) = 0x00;
								*(esp_373 - 0x0014) = 0x00;
								<anonymous> * esi_427 = ecx_419->ptr000C;
								*(esp_373 - 0x0018) = fp - 0x30;
								fn004111EF();
								word32 eax_433;
								word32 edx_435;
								esi_427();
								ecx_438 = eax_407;
								if ((byte) eax_433 != 0x00)
								{
									uint32 ebx_443 = ebx_145 - dwLoc20;
									if (ebx_443 >= *eax_407)
									{
										uint32 eax_447 = 0x01;
										if (dwLoc14 > 0x01)
										{
											while (ebx_443 >= *((word32) eax_407 + eax_447 * 0x08))
											{
												++eax_447;
												if (eax_447 >= dwLoc14)
													break;
											}
										}
										uint32 eax_463 = *((word32) (eax_407 - 0x04) + eax_447 * 0x08);
										*(esp_332 - 0x04) = 0x00;
										*(esp_332 - 0x08) = 0x00;
										*dwArg10 = eax_463 & 0x00FFFFFF;
										struct Eq_1703 * eax_478 = *dwLoc18;
										*(esp_332 - 0x0C) = 0x00;
										<anonymous> * esi_481 = eax_478->ptr0070;
										*(esp_332 - 0x0010) = fp + 0x0C;
										*(esp_332 - 0x0014) = (word16 **) dwArg08;
										*(esp_332 - 0x0018) = dwLoc30;
										fn004111EF();
										word32 eax_509;
										word32 edx_511;
										esi_481();
										ecx_438 = eax_407;
									}
								}
								goto l00414FE9;
							}
							<anonymous> * esi_524 = *((char *) null + 0x08);
							fn004111EF();
							word32 eax_537;
							word32 edx_539;
							esi_524();
						} while (eax_537 != 0x00);
					}
					ecx_438.u0 = 0x00;
l00414FE9:
					union Eq_1734 * esp_550 = esp_332 - 0x04;
					*esp_550 = (union Eq_1734 *) ecx_438;
					*(esp_550 - 0x04) = 0x00;
					*(esp_550 - 0x08) = (union Eq_2 *) GetProcessHeap();
					HeapFree(*(esp_550 - 0x08), *(esp_550 - 0x04), *esp_550);
l00414FF9:
					<anonymous> * esi_566 = *null;
					fn004111EF();
					word32 edx_597;
					esi_566();
				}
				<anonymous> * esi_604 = *((char *) *dwLoc18 + 0x0040);
				fn004111EF();
				word32 edx_619;
				esi_604();
			}
			<anonymous> * esi_626 = *((char *) *dwLoc24 + 0x0038);
			fn004111EF();
			word32 edx_641;
			esi_626();
		}
	}
	<anonymous> * esi_648 = *((char *) *dwLoc1C + 44);
	fn004111EF();
	word32 * esp_660;
	word32 edx_663;
	esi_648();
	return *esp_660;
}

// 0041140B: void fn0041140B()
void fn0041140B()
{
	SDL2.dll!SDL_ShowSimpleMessageBox();
}

// 00412490: void fn00412490(Register Eq_2 ecx, Register Eq_2 edx, Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Stack Eq_2 dwArg00)
void fn00412490(Eq_2 ecx, Eq_2 edx, struct Eq_6 * es, struct Eq_7 * ds, Eq_2 dwArg00)
{
	Eq_2 esi_20 = 0x00;
	if (*edx > 0x00)
	{
		Eq_2 edi_26 = 0x00;
		do
		{
			struct Eq_2064 * ecx_31 = *((word32) edx + 0x04);
			word32 edx_35 = Mem30[ecx_31 + edi_26:word32];
			if (Mem30[edx_35 - 0x04 + ecx:word32] == 0xCCCCCCCC)
			{
				edx_35 = ecx;
				if (Mem30[Mem30[ecx_31 + 0x04 + edi_26:word32] + edx_35 + ecx:word32] != 0xCCCCCCCC)
					goto l004124C9;
			}
			else
			{
l004124C9:
				fn004111EA(edx_35, edx, esi_20, edi_26, es, ds, dwArg00, Mem30[ecx_31 + 0x08 + edi_26:word32]);
			}
			esi_20 = (word32) esi_20 + 0x01;
			edi_26 = (word32) edi_26 + 0x0C;
		} while (esi_20 < *edx);
	}
}

// 00412500: void fn00412500(Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Stack Eq_2 dwArg00)
void fn00412500(struct Eq_6 * es, struct Eq_7 * ds, Eq_2 dwArg00)
{
	if (!Z)
		return;
	fn004112EE(es, ds, dwArg00, 0x00);
}

// 00412540: void fn00412540(Register (ptr32 byte) ecx)
void fn00412540(byte * ecx)
{
	if ((word32) *ecx != 0x00 && globals->t41B5A4 != 0x00)
		globals->t41B5A4 != GetCurrentThreadId();
}

// 00412780: Register word32 fn00412780(Register ui32 ebx, Register Eq_2 esi, Register Eq_2 edi, Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Register word128 xmm0)
word32 fn00412780(ui32 ebx, Eq_2 esi, Eq_2 edi, struct Eq_6 * es, struct Eq_7 * ds, word128 xmm0)
{
	return fn004127A0(fn00411348(), ebx, esi, edi, es, ds, xmm0);
}

// 004127A0: Register int32 fn004127A0(Register Eq_2 edx, Register ui32 ebx, Register Eq_2 esi, Register Eq_2 edi, Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Register word128 xmm0)
int32 fn004127A0(Eq_2 edx, ui32 ebx, Eq_2 esi, Eq_2 edi, struct Eq_6 * es, struct Eq_7 * ds, word128 xmm0)
{
	ptr32 eax_15 = fs->ptr0000;
	fs->ptr0000 = fp - 0x14;
	word32 * esp_107 = fp + ~0x57;
	if ((word32) (byte) (uint32) (uint8) fn00411154(edx, ebx, esi, edi, es, ds, 0x01) == 0x00)
	{
		fn00411361(0x07);
		esp_107 = fp + ~0x5B;
	}
	int32 eax_112;
	byte bLoc1D_321 = 0x00;
	byte al_85 = (byte) (uint32) (uint8) fn004113FC();
	if (globals->dw41B528 == 0x01)
	{
		esp_107 -= 0x04;
		*esp_107 = 0x07;
		fn00411361(*esp_107);
	}
	else if (globals->dw41B528 == 0x00)
	{
		globals->dw41B528 = 0x01;
		PVFV ** esp_94 = esp_107 - 0x04;
		*esp_94 = (PVFV **) &globals->t418618;
		*(esp_94 - 0x04) = 4293388;
		if (fn0041107D(*(esp_94 - 0x04), *esp_94) != 0x00)
		{
			eax_112 = 0xFF;
			goto l004129A2;
		}
		*esp_94 = (PVFV **) &globals->t418208;
		*(esp_94 - 0x04) = 0x00418000;
		fn00411221(*(esp_94 - 0x04), *esp_94);
		globals->dw41B528 = 0x02;
		esp_107 = (word32 *) ((char *) esp_94 + 0x04);
	}
	else
		bLoc1D_321 = 0x01;
	union Eq_268 * esp_128 = esp_107 - 0x04;
	*esp_128 = (word32) al_85;
	fn004110AF(*esp_128);
	ptr32 esp_137 = (char *) esp_128 + 0x04;
	Eq_268 eax_139 = fn004111E0();
	if (*eax_139 != 0x00)
	{
		*esp_128 = (union Eq_268 *) eax_139;
		esp_137 = (char *) esp_128 + 0x04;
		if ((word32) (byte) (uint32) (uint8) fn00411217(*esp_128) != 0x00)
		{
			Eq_268 eax_162 = *eax_139;
			*esp_128 = (union Eq_268 *) 0x00;
			*(esp_128 - 0x04) = 0x02;
			*(esp_128 - 0x08) = 0x00;
			fn004111EF();
			eax_162();
		}
	}
	Eq_268 eax_197 = fn004112B2();
	if (*eax_197 != 0x00)
	{
		union Eq_268 * esp_205 = esp_137 - 0x04;
		*esp_205 = (union Eq_268 *) eax_197;
		if ((word32) (byte) (uint32) (uint8) fn00411217(*esp_205) != 0x00)
		{
			*esp_205 = (union Eq_268 *) *eax_197;
			fn004110C8();
		}
	}
	int32 eax_243 = fn00412A70(es, ds, xmm0);
	if ((word32) (byte) (uint32) (uint8) fn00411230() == 0x00)
	{
		int32 * esp_266 = esp_137 - 0x04;
		*esp_266 = eax_243;
		fn004112DA(*esp_266);
	}
	if ((word32) bLoc1D_321 == 0x00)
		fn00411028();
	union Eq_823 * esp_273 = esp_137 - 0x04;
	*esp_273 = 0x00;
	*(esp_273 - 0x04) = 0x01;
	fn004112C6(*esp_273);
	eax_112 = eax_243;
l004129A2:
	fs->ptr0000 = eax_15;
	return eax_112;
}

// 00412A70: Register word32 fn00412A70(Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Register word128 xmm0)
word32 fn00412A70(struct Eq_6 * es, struct Eq_7 * ds, word128 xmm0)
{
	fn0041127B();
	fn004113B1();
	return fn00411064(es, ds, xmm0);
}

// 00412B20: Register byte fn00412B20()
byte fn00412B20()
{
	fn00413170(fp - 0x20);
	return (byte) SEQ(SLICE(eax_20, word24, 8), false);
}

// 00412B70: Register byte fn00412B70()
byte fn00412B70()
{
	fn00413170(fp - 0x20);
	return (byte) SEQ(SLICE(eax_26, word24, 8), false);
}

// 00412CF0: void fn00412CF0(Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Stack Eq_2 dwArg04, Stack uint32 dwArg08)
void fn00412CF0(struct Eq_6 * es, struct Eq_7 * ds, Eq_2 dwArg04, uint32 dwArg08)
{
	if (dwArg08 > 0x04)
	{
		Eq_2 edx_11 = globals->t418BA8;
		fn00412EF0(edx_11, es, ds, dwArg04, 0x01, 0x05, edx_11);
	}
	else
	{
		word32 ecx_41 = globals->a41B014[dwArg08 * 0x04];
		Eq_2 edx_42 = *((char *) globals->a418B94 + dwArg08 * 0x04);
		if (ecx_41 == ~0x00)
			return;
		fn00412EF0(edx_42, es, ds, dwArg04, ecx_41, dwArg08, edx_42);
	}
}

// 00412ED0: Register word32 fn00412ED0(Stack (ptr32 char) dwArg04, Register out (ptr32 char) edxOut)
word32 fn00412ED0(char * dwArg04, char & edxOut)
{
	char * eax_10 = dwArg04;
	do
	{
		eax_10 = eax_34 + 0x01;
		eax_34 = eax_10;
	} while (*eax_34 != 0x00);
	edxOut = dwArg04;
	return eax_10 - dwArg04 - 0x01;
}

// 00412EF0: Register Eq_2 fn00412EF0(Register Eq_2 edx, Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Stack Eq_2 dwArg04, Stack word32 dwArg08, Stack uint32 dwArg0C, Stack Eq_2 dwArg10)
Eq_2 fn00412EF0(Eq_2 edx, struct Eq_6 * es, struct Eq_7 * ds, Eq_2 dwArg04, word32 dwArg08, uint32 dwArg0C, Eq_2 dwArg10)
{
	ui32 eax_10 = globals->t41B004 ^ fp - 0x04;
	word32 dwLoc0E38_431 = 0x00;
	word32 eax_31 = fn004111A9();
	if (eax_31 == 0x00)
		dwLoc0E38_431 = fn00411046();
	Eq_2485 eax_57 = MultiByteToWideChar(65001, 0x00, dwArg10, ~0x00, 0x00, 0x00);
	if (eax_57 >= 0x0200 || MultiByteToWideChar(65001, 0x00, dwArg10, ~0x00, fp + ~0x0E2F, eax_57) == 0x00)
		;
	union Eq_2 * esp_124;
	byte al_101;
	if ((byte) (uint32) (uint8) fn00412B20() != 0x00)
	{
		al_101 = (byte) (uint32) (uint8) fn00412B70();
		esp_124 = fp - 3660;
		if (al_101 != 0x00)
			goto l004130DD;
	}
	else
		al_101 = 0x01;
	esp_124 = fp - 3660;
	if ((dwLoc0E38_431 != 0x00 || eax_31 != 0x00) && (al_101 == 0x00 || IsDebuggerPresent() == 0x00))
	{
		word32 eax_324;
		ptr32 esp_323;
		<anonymous> * edi_215 = fn00411401(es, ds, dwArg04 - 0x05, fp - 0x0210, fp + ~0x0E3B, fp - 0x0418, 0x0104);
		if (edi_215 != null)
		{
			fn004111EF();
			edi_215();
			esp_323 = fp - 3688;
		}
		else
		{
			WideCharToMultiByte(65001, 0x00, fp - 0x0210, ~0x00, fp - 1828, 778, 0x00, null) == 0x00;
			WideCharToMultiByte(65001, 0x00, fp - 0x0418, ~0x00, fp + ~0x0A2F, 778, 0x00, null) == 0x00;
			fn004111EF();
			fn00000000();
		}
		esp_124 = esp_323 + 0x1C;
		if (eax_324 != 0x01)
		{
l004130DD:
			struct Eq_2535 * esp_375 = (char *) esp_124 + 0x04;
			Eq_2 edx_412;
			fn00411249(eax_10 ^ fp - 0x04, edx, esp_375->t0004, fp - 0x04, esp_375->t0000, *esp_124, es, ds, esp_375->t0004, out edx_412);
			return edx_412;
		}
	}
	int3();
	goto l004130DD;
}

// 00413170: void fn00413170(Stack (ptr32 Eq_2413) dwArg04)
void fn00413170(ULONG_PTR * dwArg04)
{
	ptr32 eax_15 = fs->ptr0000;
	fs->ptr0000 = fp - 0x14;
	RaiseException(1080890248, 0x00, 0x06, dwArg04);
	fs->ptr0000 = eax_15;
}

// 00413370: Register Eq_251 fn00413370(Stack (ptr32 Eq_283) dwArg04)
Eq_251 fn00413370(struct _EXCEPTION_POINTERS * dwArg04)
{
	SetUnhandledExceptionFilter(null);
	UnhandledExceptionFilter(dwArg04);
	return TerminateProcess(GetCurrentProcess(), 0xC0000409);
}

// 004133B0: Register word32 fn004133B0(Register Eq_10 ecx, Register Eq_2 edx, Register Eq_2 ebx, Register ptr32 ebp, Register Eq_2 esi, Register Eq_2 edi, Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Stack Eq_2 dwArg00, Register out Eq_10 edxOut)
word32 fn004133B0(Eq_10 ecx, Eq_2 edx, Eq_2 ebx, ptr32 ebp, Eq_2 esi, Eq_2 edi, struct Eq_6 * es, struct Eq_7 * ds, Eq_2 dwArg00, union Eq_10 & edxOut)
{
	word32 eax_12 = fn0041106E(0x17);
	Eq_2679 SCZDOP_41 = cond(eax_12) | SCZDOP;
	if (eax_12 == 0x00)
	{
		globals->dw41B260 = eax_12;
		globals->t41B25C = ecx;
		globals->t41B258 = edx;
		globals->t41B254 = ebx;
		globals->t41B250 = esi;
		globals->t41B24C = edi;
		globals->ptr41B278 = ss;
		globals->ptr41B26C = cs;
		globals->ptr41B248 = ds;
		globals->ptr41B244 = es;
		globals->ptr41B240 = fs;
		globals->ptr41B23C = gs;
		globals->t41B270 = SCZDOP_41;
		globals->ptr41B264 = ebp;
		globals->t41B268 = dwArg00;
		globals->ptr41B274 = fp + 0x04;
		globals->dw41B1B0 = 0x00010001;
		globals->t41B16C = globals->t41B268;
		globals->dw41B160 = 0xC0000409;
		globals->dw41B164 = 0x01;
		globals->dw41B170 = 0x01;
		globals->dw41B174 = 0x02;
		Eq_10 edx_63 = globals->t41B004;
		word32 eax_72 = fn004110D2(&globals->t419250);
		edxOut = edx_63;
		return eax_72;
	}
	else
		__fastfail(0x02);
}

// 00413870: Register (ptr32 Eq_2754) fn00413870(Stack (ptr32 Eq_638) dwArg04, Stack uint32 dwArg08)
struct Eq_2754 * fn00413870(struct Eq_638 * dwArg04, uint32 dwArg08)
{
	struct Eq_2755 * edx_13 = dwArg04 + dwArg04->dw003C / 0x0040;
	struct Eq_2754 * ecx_20 = &edx_13->w0014 + 0x02 + (word32) edx_13->w0014 / 22;
	struct Eq_2754 * ecx_25 = ecx_20 + (word32) edx_13->w0006;
	struct Eq_2754 * dwLoc08_67 = ecx_20;
	while (true)
	{
		struct Eq_2754 * eax_35;
		if (dwLoc08_67 == ecx_25)
			break;
		if (dwArg08 >= dwLoc08_67->dw000C && dwArg08 < dwLoc08_67->dw000C + dwLoc08_67->dw0008)
		{
			eax_35 = dwLoc08_67;
			return eax_35;
		}
		++dwLoc08_67;
	}
	eax_35 = null;
	return eax_35;
}

// 00413920: Register byte fn00413920(Stack (ptr32 Eq_624) dwArg04)
byte fn00413920(struct Eq_624 * dwArg04)
{
	word32 eax_60;
	if (dwArg04 == null)
		eax_60 = SEQ(eax_24_8, 0x00);
	else
	{
		word24 eax_24_8_63 = SLICE(dwArg04, word24, 8);
		if ((word32) dwArg04->w0000 != 23117)
			eax_60 = SEQ(eax_24_8_63, 0x00);
		else
		{
			struct Eq_2810 * ecx_19 = dwArg04 + dwArg04->dw003C / 0x0040;
			word24 eax_24_8_65 = SLICE(ecx_19, word24, 8);
			if (ecx_19->dw0000 != 0x4550)
				eax_60 = SEQ(eax_24_8_65, 0x00);
			else
			{
				word32 eax_30 = (word32) ecx_19->w0018;
				word24 eax_24_8_67 = SLICE(eax_30, word24, 8);
				if (eax_30 != 0x010B)
					eax_60 = SEQ(eax_24_8_67, 0x00);
				else
					eax_60 = SEQ(eax_24_8_67, 0x01);
			}
		}
	}
	return (byte) eax_60;
}

// 00413BB0: Register byte fn00413BB0(Register Eq_2 edx, Register ui32 ebx, Register Eq_2 esi, Register Eq_2 edi, Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Stack word32 dwArg04)
byte fn00413BB0(Eq_2 edx, ui32 ebx, Eq_2 esi, Eq_2 edi, struct Eq_6 * es, struct Eq_7 * ds, word32 dwArg04)
{
	if (dwArg04 == 0x00)
		globals->b41B530 = 0x01;
	word32 eax_73;
	fn00411014(edx, ebx, esi, edi, es, ds);
	word32 eax_41 = (word32) fn00411177();
	word24 eax_24_8_74 = SLICE(eax_41, word24, 8);
	if (eax_41 == 0x00)
		eax_73 = SEQ(eax_24_8_74, 0x00);
	else if ((word32) fn0041135C() == 0x00)
	{
		fn0041110E();
		eax_73 = SEQ(eax_24_8_74, 0x00);
	}
	else
		eax_73 = SEQ(eax_24_8_74, 0x01);
	return (byte) eax_73;
}

// 00414030: Register ui32 fn00414030()
ui32 fn00414030()
{
	GetSystemTimeAsFileTime(fp - 0x10);
	ui32 eax_25 = GetCurrentProcessId() ^ (GetCurrentThreadId() ^ 0x00);
	QueryPerformanceCounter(fp - 0x18);
	return eax_25 ^ dwLoc18 ^ dwLoc14 ^ fp - 0x08;
}

// 004140C0: Register word32 fn004140C0()
word32 fn004140C0()
{
	if (globals->t41B004 != 0xBB40E64E && (globals->t41B004 & 0xFFFF0000) != 0x00)
		globals->dw41B000 = ~globals->t41B004;
	else
	{
		Eq_10 eax_18 = fn00414030();
		Eq_10 dwLoc08_59 = eax_18;
		if (eax_18 == 0xBB40E64E)
			dwLoc08_59.u0 = ~0x44BF19B0;
		else if ((eax_18 & 0xFFFF0000) == 0x00)
			dwLoc08_59 = (eax_18 | 0x4711) << 0x10 | eax_18;
		globals->t41B004 = dwLoc08_59;
		edx = ~dwLoc08_59;
		globals->dw41B000 = edx;
	}
	return edx;
}

// 00414690: void fn00414690()
void fn00414690()
{
	globals->dw41B574 = 0x00;
}

// 00414810: Register word32 fn00414810(Register Eq_2 edx, Register Eq_2 ebx, Register Eq_2 esi, Register Eq_2 edi, Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Register out Eq_2 ebxOut)
word32 fn00414810(Eq_2 edx, Eq_2 ebx, Eq_2 esi, Eq_2 edi, struct Eq_6 * es, struct Eq_7 * ds, union Eq_2 & ebxOut)
{
	ui32 eax_10 = globals->t41B004 ^ fp - 0x04;
	if (globals->b41B57C != 0x00)
	{
l00414940:
		goto l00414942;
	}
	globals->b41B57C = 0x01;
	Eq_2 eax_104 = fn004149A0(edx, es, ds, out edx, out ebx, out esi, out edi);
	if (eax_104 == 0x00)
	{
		fn0041114F();
		if (eax_104 == 0x00)
		{
l004148CD:
			fn00411357();
			dwLoc041C.u0 = 0x0A00;
			if (eax_104 == 0x00)
			{
				if (GetLastError() != 0x57)
					goto l00414940;
				fn00411078();
				dwLoc041C.u0 = 0x0104;
				if (fp == 0x0418)
					goto l00414940;
				dwLoc041C.u0 = 0x0104;
				if (fn00414C90(edx, ebx, esi, edi, es, ds, fp - 0x0418, fp - 0x0210, 0x0104, out edx) == 0x00)
					goto l00414940;
				fn00411357();
				dwLoc041C.u0 = 0x08;
				if (fp == 0x0210)
					goto l00414940;
			}
			goto l00414942;
		}
		fn00411078();
		if (eax_104 == 0x00)
			goto l004148CD;
		eax_104 = fn00414C90(edx, ebx, esi, edi, es, ds, fp - 0x0418, fp - 0x0210, 0x0104, out edx);
		if (eax_104 == 0x00)
			goto l004148CD;
		fn00411357();
		dwLoc041C.u0 = 0x0900;
		if (fp == 0x0210)
		{
			eax_104 = GetLastError();
			if (eax_104 != 0x57)
				goto l004148CD;
			fn00411357();
			dwLoc041C.u0 = 0x08;
			eax_104 = fp - 0x0210;
			if (fp == 0x0210)
				goto l004148CD;
		}
	}
l00414942:
	word32 edx_249;
	word32 eax_199 = fn00411249(eax_10 ^ fp - 0x04, edx, ebx, fp - 0x04, esi, edi, es, ds, dwLoc041C, out edx_249);
	ebxOut = ebx;
	return eax_199;
}

// 004149A0: Register word32 fn004149A0(Register Eq_2 edx, Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Register out ptr32 edxOut, Register out Eq_2 ebxOut, Register out Eq_2 esiOut, Register out Eq_2 ediOut)
word32 fn004149A0(Eq_2 edx, struct Eq_6 * es, struct Eq_7 * ds, ptr32 & edxOut, union Eq_2 & ebxOut, union Eq_2 & esiOut, union Eq_2 & ediOut)
{
	union Eq_2 * esp_153;
	Eq_2 eax_10 = globals->t41B004 ^ fp - 0x04;
	fn00411357();
	Eq_2 edi_29 = eax_10;
	if (eax_10 != 0x00)
	{
l00414A09:
		Eq_1562 eax_65 = GetProcAddress(edi_29, &globals->t419410);
		esp_153 = fp - 0x022C;
		if (eax_65 != null)
		{
			Eq_1562 eax_75 = GetProcAddress(edi_29, &globals->t419420);
			esp_153 = fp - 0x022C;
			if (eax_75 != null)
			{
				Eq_1562 eax_85 = GetProcAddress(edi_29, &globals->t419434);
				esp_153 = fp - 0x022C;
				if (eax_85 != null)
				{
					fn004111EF();
					edx.u0 = <invalid>;
					if (eax_65() != 0x00)
					{
						FreeLibrary(edi_29);
						esp_153 = fp - 0x0240;
					}
					else
					{
						fn004111EF();
						int32 eax_133 = eax_75();
						fn004111EF();
						eax_85();
						FreeLibrary(edi_29);
						word16 si_170 = (word16) eax_133;
						edx.u0 = <invalid>;
						esp_153 = fp - 0x025C;
						if (eax_133 == 0x00 && (dwLoc0220 == 0x01 && true))
						{
							edx.u0 = 0x0104;
							if (true)
							{
								uint32 ecx_168 = 0x0103;
								if (wLoc0A == si_170)
								{
									if (wLoc0C != 0x5C)
										ecx_168 = 0x0104;
									if (~ecx_168 >= 0x12 && ecx_168 <= ~0xF2)
									{
										(fp - 0x0210)[ecx_168].dw0000 = globals->dw419340;
										(fp - 0x020C)[ecx_168].dw0000 = globals->dw419344;
										(fp - 0x0208)[ecx_168].dw0000 = globals->dw419348;
										(fp - 0x0204)[ecx_168].dw0000 = globals->dw41934C;
										(fp - 0x0200)[ecx_168].dw0000 = globals->dw419350;
										(fp - 0x01FC)[ecx_168].dw0000 = globals->dw419354;
										(fp - 0x01F8)[ecx_168].dw0000 = globals->dw419358;
										(fp - 500)[ecx_168].dw0000 = globals->dw41935C;
										(fp - 0x01F0)[ecx_168] = globals->w419360;
										fn00411357();
										if (fp == 0x0210 && GetLastError() == 0x57)
											fn00411357();
										ptr32 edx_277;
										word32 eax_275 = fn00411249(eax_10 ^ fp - 0x04, 0x0104, 0x004194D4, fp - 0x04, dwLoc0214, dwLoc0214, es, ds, 0x004194D4, out edx_277);
										edxOut = edx_277;
										ebxOut.u0 = 0x004194D4;
										esiOut = dwLoc0214;
										ediOut = dwLoc0214;
										return eax_275;
									}
								}
							}
						}
					}
				}
			}
		}
		goto l00414A6D;
	}
	else
	{
		fn00411357();
		edi_29 = eax_10;
		esp_153 = fp - 0x022C;
		if (eax_10 != 0x00)
			goto l00414A09;
		Eq_2 eax_45 = GetLastError();
		if (eax_45 == 0x57)
		{
			fn00411357();
			edi_29 = eax_45;
			esp_153 = fp - 0x022C;
			if (eax_45 != 0x00)
				goto l00414A09;
		}
l00414A6D:
		struct Eq_3095 * esp_292 = (char *) esp_153 + 0x04;
		Eq_2 edi_291 = *esp_153;
		Eq_2 esi_293 = esp_292->t0000;
		Eq_2 ebx_296 = esp_292->t0004;
		ptr32 edx_314;
		word32 eax_312 = fn00411249(eax_10 ^ fp - 0x04, edx, ebx_296, fp - 0x04, esi_293, edi_291, es, ds, esp_292->t0004, out edx_314);
		edxOut = edx_314;
		ebxOut = ebx_296;
		esiOut = esi_293;
		ediOut = edi_291;
		return eax_312;
	}
}

// 00414C90: Register word32 fn00414C90(Register Eq_2 edx, Register Eq_2 ebx, Register Eq_2 esi, Register Eq_2 edi, Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Stack (ptr32 wchar_t) dwArg04, Stack (ptr32 wchar_t) dwArg08, Stack Eq_2 dwArg0C, Register out ptr32 edxOut)
word32 fn00414C90(Eq_2 edx, Eq_2 ebx, Eq_2 esi, Eq_2 edi, struct Eq_6 * es, struct Eq_7 * ds, wchar_t * dwArg04, wchar_t * dwArg08, Eq_2 dwArg0C, ptr32 & edxOut)
{
	ui32 eax_10 = globals->t41B004 ^ fp - 0x04;
	if (fn004112E9(dwArg04, fp - 0x10, 0x03, fp - 0x0610, 0x0100, fp - 0x0410, 0x0100, fp - 0x0210, 0x0100) != 0x00 || (fn004113CF(fp - 0x0410, 0x09, "M\0S\0P\0D\0B\01\04\00\0\0") != 0x00 || (fn004113CF(fp - 0x0210, 0x04, "D\0L\0L\0\0") != 0x00 || fn0041119A(dwArg08, dwArg0C, fp - 0x10, fp - 0x0610, fp - 0x0410, fp - 0x0210) != 0x00)))
	{
		ptr32 edx_122;
		word32 eax_120 = fn00411249(eax_10 ^ fp - 0x04, edx, ebx, fp - 0x04, esi, edi, es, ds, esi, out edx_122);
		edxOut = edx_122;
		return eax_120;
	}
	else
	{
		ptr32 edx_139;
		word32 eax_137 = fn00411249(eax_10 ^ fp - 0x04, edx, ebx, fp - 0x04, esi, edi, es, ds, esi, out edx_139);
		edxOut = edx_139;
		return eax_137;
	}
}

// 004157C0: void fn004157C0(Stack Eq_2595 dwArg04, Stack Eq_1734 dwArg08)
void fn004157C0(Eq_2595 dwArg04, Eq_1734 dwArg08)
{
	Eq_2595 eax_101 = dwArg04;
	ui32 esi_140 = 0x00;
	ui32 edi_148 = 0x00;
	if (*dwArg04 != 0x00)
	{
		do
		{
			while (true)
			{
				byte cl_24 = *eax_101;
				if (cl_24 != 0x20 && cl_24 != 0x09)
					break;
				eax_101 = (word32) eax_101 + 0x01;
			}
			word32 edx_425;
			if (cl_24 == 0x22)
			{
				byte cl_67 = *((word32) eax_101 + 0x01);
				eax_101 = (word32) eax_101 + 0x01;
				if (cl_67 != 0x00)
				{
					if (dwArg08 != 0x00)
					{
						*((word32) dwArg08 + edi_148 * 0x04) = eax_101;
						cl_67 = (byte) *eax_101;
					}
					++edi_148;
				}
				Eq_2595 edx_100 = eax_101;
				word24 edx_24_8_383 = SLICE(eax_101, word24, 8);
				while (cl_67 != 0x00)
				{
					edx_24_8_383 = SLICE(edx_100, word24, 8);
					if (cl_67 == 0x22 && *edx_100 != 0x5C)
						break;
					cl_67 = (byte) *((word32) eax_101 + 0x01);
					edx_100 = eax_101;
					edx_24_8_383 = SLICE(eax_101, word24, 8);
					eax_101 = (word32) eax_101 + 0x01;
				}
				edx_425 = SEQ(edx_24_8_383, *eax_101);
				goto l00415848;
			}
			if (cl_24 != 0x00)
			{
				if (dwArg08 != 0x00)
				{
					*((word32) dwArg08 + edi_148 * 0x04) = eax_101;
					cl_24 = (byte) *eax_101;
				}
				word24 edx_24_8_388 = SLICE(dwArg08, word24, 8);
				++edi_148;
				if (cl_24 == 0x00)
					goto l00415859;
				do
				{
					edx_425 = SEQ(edx_24_8_388, cl_24);
					if (cl_24 == 0x20)
						break;
					edx_425 = SEQ(edx_24_8_388, cl_24);
					if (cl_24 == 0x09)
						break;
					byte dl_61 = *((word32) eax_101 + 0x01);
					eax_101 = (word32) eax_101 + 0x01;
					cl_24 = dl_61;
					edx_425 = SEQ(edx_24_8_388, dl_61);
				} while (dl_61 != 0x00);
l00415848:
				if ((byte) edx_425 != 0x00)
				{
					if (dwArg08 != 0x00)
						*eax_101 = 0x00;
					eax_101 = (word32) eax_101 + 0x01;
				}
			}
			else
			{
l00415859:
			}
			if (dwArg08 != 0x00 && esi_140 != edi_148)
			{
				Eq_2595 esi_161 = *((word32) dwArg08 + esi_140 * 0x04);
				Eq_2595 edx_162 = 0x00;
				byte cl_163 = *esi_161;
				while (cl_163 != 0x00)
				{
					if (cl_163 == 0x22 && (edx_162 != 0x00 && *edx_162 == 0x5C))
					{
						Eq_2595 ecx_178 = esi_161;
						byte bl_179 = 0x22;
						do
						{
							*edx_162 = bl_179;
							edx_162 = ecx_430;
							bl_179 = (byte) *((word32) ecx_430 + 0x01);
							ecx_178 = (word32) ecx_430 + 0x01;
							ecx_430 = ecx_178;
						} while (bl_179 != 0x00);
						*ecx_430 = bl_179;
					}
					cl_163 = (byte) *((word32) esi_161 + 0x01);
					edx_162 = esi_161;
					esi_161 = (word32) esi_161 + 0x01;
				}
			}
			esi_140 = edi_148;
		} while (*eax_101 != 0x00);
	}
	if (dwArg08 != 0x00)
		*((word32) dwArg08 + edi_148 * 0x04) = 0x00;
}

// 00415920: Register word32 fn00415920(Register (ptr16 Eq_6) es, Register (ptr16 Eq_7) ds, Register word128 xmm0)
word32 fn00415920(struct Eq_6 * es, struct Eq_7 * ds, word128 xmm0)
{
	Eq_2492 eax_18 = GetCommandLineW();
	word32 eax_22 = (word32) *eax_18;
	ui32 esi_20 = 0x02;
	word32 edx_21 = eax_18 + 0x02;
	if ((word16) eax_22 != 0x00)
	{
		word16 cx_236 = (word16) eax_22;
		do
		{
			if (cx_236 == 0x20 || cx_236 == 0x09)
				++esi_20;
			word32 eax_43 = (word32) *edx_21;
			edx_21 += 0x02;
			cx_236 = (word16) eax_43;
		} while ((word16) eax_43 != 0x00);
	}
	int32 eax_74 = WideCharToMultiByte(65001, 0x00, eax_18, ~0x00, 0x00, 0x00, 0x00, null);
	if (eax_74 > 0x00)
	{
		Eq_1449 eax_87 = eax_74 + esi_20 * 0x04;
		Eq_1734 eax_95 = VirtualAlloc(0x00, eax_87, 0x3000, 0x04);
		if (eax_95 != 0x00)
		{
			word32 esi_108 = eax_95 + esi_20 * 0x04;
			WideCharToMultiByte(65001, 0x00, eax_18, ~0x00, esi_108, eax_74, 0x00, null);
			if (esi_108 != 0x00)
			{
				fn004157C0(esi_108, eax_95);
				fn004111CC();
				Eq_1734 ebx_196;
				word32 eax_195 = fn00411307(es, ds, xmm0, out ebx_196);
				VirtualFree(ebx_196, eax_87, 0x4000);
				VirtualFree(ebx_196, 0x00, 0x8000);
				return eax_195;
			}
		}
	}
	fn0041140B();
	return 0x00;
}

