// DataGrapher.globals.c
// Generated by decompiling DataGrapher.exe
// using Reko decompiler version 0.9.1.0.

#include "DataGrapher.h"

struct Eq_1737 * g_ptr0000;
Eq_624 g_t400000 = 
	{
		0x0000,
		0,
	};
Eq_260 g_t418208 = null;
Eq_260 g_t418618 = null;
Eq_397 g_t418B40 = 
	{
		0.0F
	};
WCHAR g_t418B44 = L'C';
Eq_2 g_a418B94[] = 
	{
	};
Eq_2 g_t418BA8 = 
	{
		0x00418F50
	};
char g_str418BC4[] = "Stack around the variable '";
char g_str418BE0[] = "' was corrupted.";
Eq_283 g_t419250 = 
	{
		&g_dw41B160,
		&g_dw41B1B0,
	};
word32 g_dw419340 = 0x00690062;
word32 g_dw419344 = 0x005C006E;
word32 g_dw419348 = 0x0053004D;
word32 g_dw41934C = 0x00440050;
word32 g_dw419350 = 0x00310042;
word32 g_dw419354 = 0x00300034;
word32 g_dw419358 = 0x0044002E;
word32 g_dw41935C = 0x004C004C;
word16 g_w419360 = 0x0000;
CHAR g_t419410 = 'R';
CHAR g_t419420 = 'R';
CHAR g_t419434 = 'R';
wchar_t g_str4194F0[] = "D\0L\0L\0\0";
wchar_t g_str4194FC[] = "M\0S\0P\0D\0B\01\04\00\0\0";
CHAR g_t41952C = 'P';
word32 g_dw41B000 = 0x44BF19B1;
Eq_10 g_t41B004 = 
	{
		0xBB40E64E
	};
word32 g_a41B014[] = 
	{
	};
word32 g_dw41B01C = 0x00000001;
ui32 g_dw41B034 = 0x00000001;
word32 g_dw41B038 = 0x00000001;
word32 g_dw41B160 = 0x00000000;
word32 g_dw41B164 = 0x00000000;
Eq_2 g_t41B16C = 
	{
		0x00000000
	};
word32 g_dw41B170 = 0x00000000;
word32 g_dw41B174 = 0x00000000;
word32 g_dw41B1B0 = 0x00000000;
struct Eq_2710 * g_ptr41B23C = null;
struct Eq_2707 * g_ptr41B240 = null;
struct Eq_6 * g_ptr41B244 = null;
struct Eq_7 * g_ptr41B248 = null;
Eq_2 g_t41B24C = 
	{
		0x00000000
	};
Eq_2 g_t41B250 = 
	{
		0x00000000
	};
Eq_2 g_t41B254 = 
	{
		0x00000000
	};
Eq_2 g_t41B258 = 
	{
		0x00000000
	};
Eq_10 g_t41B25C = 
	{
		0x00000000
	};
word32 g_dw41B260 = 0x00000000;
ptr32 g_ptr41B264 = 0x00000000;
Eq_2 g_t41B268 = 
	{
		0x00000000
	};
struct Eq_2700 * g_ptr41B26C = null;
Eq_2679 g_t41B270 = 
	{
		0x00
	};
ptr32 g_ptr41B274 = 0x00000000;
struct Eq_2697 * g_ptr41B278 = null;
word32 g_dw41B51C = 0x00000000;
word32 g_dw41B520 = 0x00000000;
word32 g_dw41B528 = 0x00000000;
word32 g_dw41B52C = 0x00000000;
byte g_b41B530 = 0x00;
word32 g_dw41B574 = 0x00000000;
Eq_2 g_t41B578 = 
	{
		0x00000000
	};
byte g_b41B57C = 0x00;
byte g_b41B57D = 0x00;
word32 g_dw41B580 = 0x00000000;
ui32 g_dw41B584 = 0x00000000;
Eq_2 g_t41B5A4 = 
	{
		0x00000000
	};
byte g_b41D02F = 0x01;
byte g_b41D049 = 0x01;

