// SDL2.globals.c
// Generated by decompiling SDL2.dll
// using Reko decompiler version 0.9.1.0.

#include "SDL2.h"

Eq_6917 g_t0080;
Eq_6826 g_t6C940000 = 
	{
		0x5A4D,
		128,
	};
struct Eq_6917 * g_ptr6C94003C = &g_t0080;
<anonymous> g_t6C9527A0 = <code>;
<anonymous> g_t6C9527C0 = <code>;
<anonymous> g_t6C9527E0 = <code>;
<anonymous> g_t6C952820 = <code>;
<anonymous> g_t6C952880 = <code>;
<anonymous> g_t6C9528C0 = <code>;
<anonymous> g_t6C9528E0 = <code>;
<anonymous> g_t6C952920 = <code>;
<anonymous> g_t6C952930 = <code>;
<anonymous> g_t6C952950 = <code>;
<anonymous> g_t6C952A00 = <code>;
<anonymous> g_t6C952A30 = <code>;
<anonymous> g_t6C952A50 = <code>;
<anonymous> g_t6C952AA0 = <code>;
<anonymous> g_t6C952AD0 = <code>;
<anonymous> g_t6C952B30 = <code>;
<anonymous> g_t6C952BA0 = <code>;
<anonymous> g_t6C952BC0 = <code>;
<anonymous> g_t6C952BE0 = <code>;
<anonymous> g_t6C952C20 = <code>;
<anonymous> g_t6C952C80 = <code>;
<anonymous> g_t6C952CA0 = <code>;
<anonymous> g_t6C952CC0 = <code>;
<anonymous> g_t6C952CE0 = <code>;
<anonymous> g_t6C952D30 = <code>;
<anonymous> g_t6C952D50 = <code>;
<anonymous> g_t6C952D70 = <code>;
<anonymous> g_t6C952DB0 = <code>;
<anonymous> g_t6C952DD0 = <code>;
<anonymous> g_t6C952DF0 = <code>;
<anonymous> g_t6C952E30 = <code>;
<anonymous> g_t6C952E50 = <code>;
<anonymous> g_t6C952ED0 = <code>;
<anonymous> g_t6C952EF0 = <code>;
<anonymous> g_t6C952F10 = <code>;
<anonymous> g_t6C952F40 = <code>;
<anonymous> g_t6C952F60 = <code>;
<anonymous> g_t6C952F80 = <code>;
<anonymous> g_t6C952FD0 = <code>;
<anonymous> g_t6C952FF0 = <code>;
<anonymous> g_t6C953010 = <code>;
<anonymous> g_t6C953040 = <code>;
<anonymous> g_t6C953070 = <code>;
<anonymous> g_t6C9530D0 = <code>;
<anonymous> g_t6C9530F0 = <code>;
<anonymous> g_t6C953110 = <code>;
<anonymous> g_t6C953160 = <code>;
<anonymous> g_t6C953180 = <code>;
<anonymous> g_t6C9531B0 = <code>;
<anonymous> g_t6C9531F0 = <code>;
<anonymous> g_t6C953210 = <code>;
<anonymous> g_t6C953230 = <code>;
<anonymous> g_t6C953270 = <code>;
<anonymous> g_t6C9532A0 = <code>;
<anonymous> g_t6C953330 = <code>;
<anonymous> g_t6C953340 = <code>;
<anonymous> g_t6C953380 = <code>;
<anonymous> g_t6C9533C0 = <code>;
<anonymous> g_t6C9533F0 = <code>;
<anonymous> g_t6C953450 = <code>;
<anonymous> g_t6C953490 = <code>;
<anonymous> g_t6C9534F0 = <code>;
<anonymous> g_t6C953510 = <code>;
<anonymous> g_t6C953560 = <code>;
<anonymous> g_t6C9535A0 = <code>;
<anonymous> g_t6C9535C0 = <code>;
<anonymous> g_t6C9535F0 = <code>;
<anonymous> g_t6C953610 = <code>;
<anonymous> g_t6C953630 = <code>;
<anonymous> g_t6C953670 = <code>;
<anonymous> g_t6C953690 = <code>;
<anonymous> g_t6C9536B0 = <code>;
<anonymous> g_t6C9536F0 = <code>;
<anonymous> g_t6C953710 = <code>;
<anonymous> g_t6C953730 = <code>;
<anonymous> g_t6C9537B0 = <code>;
<anonymous> g_t6C953800 = <code>;
<anonymous> g_t6C953820 = <code>;
<anonymous> g_t6C953870 = <code>;
<anonymous> g_t6C953890 = <code>;
<anonymous> g_t6C9538B0 = <code>;
<anonymous> g_t6C9538F0 = <code>;
<anonymous> g_t6C953920 = <code>;
<anonymous> g_t6C953970 = <code>;
<anonymous> g_t6C9539B0 = <code>;
<anonymous> g_t6C9539D0 = <code>;
<anonymous> g_t6C9539F0 = <code>;
<anonymous> g_t6C953A50 = <code>;
<anonymous> g_t6C953AA0 = <code>;
<anonymous> g_t6C953AC0 = <code>;
<anonymous> g_t6C953B10 = <code>;
<anonymous> g_t6C953B30 = <code>;
<anonymous> g_t6C953B60 = <code>;
<anonymous> g_t6C953BA0 = <code>;
<anonymous> g_t6C953BC0 = <code>;
<anonymous> g_t6C953BF0 = <code>;
<anonymous> g_t6C953C20 = <code>;
<anonymous> g_t6C953C30 = <code>;
<anonymous> g_t6C953C80 = <code>;
<anonymous> g_t6C953CA0 = <code>;
<anonymous> g_t6C953CC0 = <code>;
<anonymous> g_t6C953CF0 = <code>;
<anonymous> g_t6C953D20 = <code>;
<anonymous> g_t6C953D50 = <code>;
<anonymous> g_t6C953D70 = <code>;
<anonymous> g_t6C953D90 = <code>;
<anonymous> g_t6C953DD0 = <code>;
<anonymous> g_t6C953DF0 = <code>;
<anonymous> g_t6C953E10 = <code>;
<anonymous> g_t6C953E60 = <code>;
<anonymous> g_t6C953EA0 = <code>;
<anonymous> g_t6C953EC0 = <code>;
<anonymous> g_t6C953F10 = <code>;
<anonymous> g_t6C953F30 = <code>;
<anonymous> g_t6C953F60 = <code>;
<anonymous> g_t6C953FA0 = <code>;
<anonymous> g_t6C953FC0 = <code>;
<anonymous> g_t6C953FE0 = <code>;
<anonymous> g_t6C954020 = <code>;
<anonymous> g_t6C954050 = <code>;
<anonymous> g_t6C954080 = <code>;
<anonymous> g_t6C9540E0 = <code>;
<anonymous> g_t6C954110 = <code>;
<anonymous> g_t6C954140 = <code>;
<anonymous> g_t6C9541A0 = <code>;
<anonymous> g_t6C9541C0 = <code>;
<anonymous> g_t6C9541F0 = <code>;
<anonymous> g_t6C954230 = <code>;
<anonymous> g_t6C954250 = <code>;
<anonymous> g_t6C954270 = <code>;
<anonymous> g_t6C9542B0 = <code>;
<anonymous> g_t6C9542D0 = <code>;
<anonymous> g_t6C954330 = <code>;
<anonymous> g_t6C954370 = <code>;
<anonymous> g_t6C954390 = <code>;
<anonymous> g_t6C9543B0 = <code>;
<anonymous> g_t6C954400 = <code>;
<anonymous> g_t6C954420 = <code>;
<anonymous> g_t6C954450 = <code>;
<anonymous> g_t6C954490 = <code>;
<anonymous> g_t6C9544B0 = <code>;
<anonymous> g_t6C9544C0 = <code>;
<anonymous> g_t6C9544D0 = <code>;
<anonymous> g_t6C9544F0 = <code>;
<anonymous> g_t6C954510 = <code>;
<anonymous> g_t6C954530 = <code>;
<anonymous> g_t6C954540 = <code>;
<anonymous> g_t6C954560 = <code>;
<anonymous> g_t6C9545B0 = <code>;
<anonymous> g_t6C9545D0 = <code>;
<anonymous> g_t6C954620 = <code>;
<anonymous> g_t6C954640 = <code>;
<anonymous> g_t6C954650 = <code>;
<anonymous> g_t6C954670 = <code>;
<anonymous> g_t6C9546A0 = <code>;
<anonymous> g_t6C9546C0 = <code>;
<anonymous> g_t6C9546D0 = <code>;
<anonymous> g_t6C9546F0 = <code>;
<anonymous> g_t6C954710 = <code>;
<anonymous> g_t6C954730 = <code>;
<anonymous> g_t6C954750 = <code>;
<anonymous> g_t6C954770 = <code>;
<anonymous> g_t6C9547F0 = <code>;
<anonymous> g_t6C954830 = <code>;
<anonymous> g_t6C954870 = <code>;
<anonymous> g_t6C9548F0 = <code>;
<anonymous> g_t6C954920 = <code>;
<anonymous> g_t6C9549A0 = <code>;
<anonymous> g_t6C954A00 = <code>;
<anonymous> g_t6C954A20 = <code>;
<anonymous> g_t6C954A40 = <code>;
<anonymous> g_t6C954A80 = <code>;
<anonymous> g_t6C954AA0 = <code>;
<anonymous> g_t6C954AD0 = <code>;
<anonymous> g_t6C954B50 = <code>;
<anonymous> g_t6C954B70 = <code>;
<anonymous> g_t6C954BA0 = <code>;
<anonymous> g_t6C954BF0 = <code>;
<anonymous> g_t6C954C10 = <code>;
<anonymous> g_t6C954C50 = <code>;
<anonymous> g_t6C954CE0 = <code>;
<anonymous> g_t6C954DA0 = <code>;
<anonymous> g_t6C954DF0 = <code>;
<anonymous> g_t6C954E10 = <code>;
<anonymous> g_t6C954E60 = <code>;
<anonymous> g_t6C954E80 = <code>;
<anonymous> g_t6C954EB0 = <code>;
<anonymous> g_t6C954F10 = <code>;
<anonymous> g_t6C954F40 = <code>;
<anonymous> g_t6C954F70 = <code>;
<anonymous> g_t6C954FC0 = <code>;
<anonymous> g_t6C954FF0 = <code>;
<anonymous> g_t6C955020 = <code>;
<anonymous> g_t6C955080 = <code>;
<anonymous> g_t6C9550B0 = <code>;
<anonymous> g_t6C9550E0 = <code>;
<anonymous> g_t6C955150 = <code>;
<anonymous> g_t6C955180 = <code>;
<anonymous> g_t6C9551A0 = <code>;
<anonymous> g_t6C9551F0 = <code>;
<anonymous> g_t6C955220 = <code>;
<anonymous> g_t6C955250 = <code>;
<anonymous> g_t6C9552B0 = <code>;
<anonymous> g_t6C9552E0 = <code>;
<anonymous> g_t6C955300 = <code>;
<anonymous> g_t6C955360 = <code>;
<anonymous> g_t6C9553A0 = <code>;
<anonymous> g_t6C9553D0 = <code>;
<anonymous> g_t6C955430 = <code>;
<anonymous> g_t6C955460 = <code>;
<anonymous> g_t6C955480 = <code>;
<anonymous> g_t6C9554C0 = <code>;
<anonymous> g_t6C9554E0 = <code>;
<anonymous> g_t6C955500 = <code>;
<anonymous> g_t6C955540 = <code>;
<anonymous> g_t6C955570 = <code>;
<anonymous> g_t6C9555A0 = <code>;
<anonymous> g_t6C9555F0 = <code>;
<anonymous> g_t6C955620 = <code>;
<anonymous> g_t6C955650 = <code>;
<anonymous> g_t6C9556A0 = <code>;
<anonymous> g_t6C9556D0 = <code>;
<anonymous> g_t6C955700 = <code>;
<anonymous> g_t6C955750 = <code>;
<anonymous> g_t6C955770 = <code>;
<anonymous> g_t6C955790 = <code>;
<anonymous> g_t6C9557D0 = <code>;
<anonymous> g_t6C955810 = <code>;
<anonymous> g_t6C955840 = <code>;
<anonymous> g_t6C955860 = <code>;
<anonymous> g_t6C955880 = <code>;
<anonymous> g_t6C9558A0 = <code>;
<anonymous> g_t6C9558E0 = <code>;
<anonymous> g_t6C955910 = <code>;
<anonymous> g_t6C955930 = <code>;
<anonymous> g_t6C9559C0 = <code>;
<anonymous> g_t6C9559F0 = <code>;
<anonymous> g_t6C955A10 = <code>;
<anonymous> g_t6C955A60 = <code>;
<anonymous> g_t6C955A90 = <code>;
<anonymous> g_t6C955AC0 = <code>;
<anonymous> g_t6C955B00 = <code>;
<anonymous> g_t6C955B20 = <code>;
<anonymous> g_t6C955B40 = <code>;
<anonymous> g_t6C955B80 = <code>;
<anonymous> g_t6C955BC0 = <code>;
<anonymous> g_t6C955BE0 = <code>;
<anonymous> g_t6C955C00 = <code>;
<anonymous> g_t6C955CA0 = <code>;
<anonymous> g_t6C955D10 = <code>;
<anonymous> g_t6C955D50 = <code>;
<anonymous> g_t6C955DA0 = <code>;
<anonymous> g_t6C955DD0 = <code>;
<anonymous> g_t6C955DF0 = <code>;
<anonymous> g_t6C955E70 = <code>;
<anonymous> g_t6C955EA0 = <code>;
<anonymous> g_t6C955ED0 = <code>;
<anonymous> g_t6C955F10 = <code>;
<anonymous> g_t6C955F30 = <code>;
<anonymous> g_t6C955F80 = <code>;
<anonymous> g_t6C956010 = <code>;
<anonymous> g_t6C956050 = <code>;
<anonymous> g_t6C956070 = <code>;
<anonymous> g_t6C9560B0 = <code>;
<anonymous> g_t6C9560D0 = <code>;
<anonymous> g_t6C956100 = <code>;
<anonymous> g_t6C956150 = <code>;
<anonymous> g_t6C956170 = <code>;
<anonymous> g_t6C956190 = <code>;
<anonymous> g_t6C9561F0 = <code>;
<anonymous> g_t6C956270 = <code>;
<anonymous> g_t6C9562B0 = <code>;
<anonymous> g_t6C9562F0 = <code>;
<anonymous> g_t6C956310 = <code>;
<anonymous> g_t6C956340 = <code>;
<anonymous> g_t6C9563C0 = <code>;
<anonymous> g_t6C956410 = <code>;
<anonymous> g_t6C956430 = <code>;
<anonymous> g_t6C9564B0 = <code>;
<anonymous> g_t6C9564D0 = <code>;
<anonymous> g_t6C9564F0 = <code>;
<anonymous> g_t6C956540 = <code>;
<anonymous> g_t6C956590 = <code>;
<anonymous> g_t6C9565B0 = <code>;
<anonymous> g_t6C956610 = <code>;
<anonymous> g_t6C956650 = <code>;
<anonymous> g_t6C956680 = <code>;
<anonymous> g_t6C9566D0 = <code>;
<anonymous> g_t6C9566F0 = <code>;
<anonymous> g_t6C956700 = <code>;
<anonymous> g_t6C956790 = <code>;
<anonymous> g_t6C9567E0 = <code>;
<anonymous> g_t6C956840 = <code>;
<anonymous> g_t6C9568A0 = <code>;
<anonymous> g_t6C9568E0 = <code>;
<anonymous> g_t6C956900 = <code>;
<anonymous> g_t6C956940 = <code>;
<anonymous> g_t6C956960 = <code>;
<anonymous> g_t6C9569B0 = <code>;
<anonymous> g_t6C956A30 = <code>;
<anonymous> g_t6C956A60 = <code>;
<anonymous> g_t6C956A80 = <code>;
<anonymous> g_t6C956AC0 = <code>;
<anonymous> g_t6C956AE0 = <code>;
<anonymous> g_t6C956AF0 = <code>;
<anonymous> g_t6C956B30 = <code>;
<anonymous> g_t6C956B50 = <code>;
<anonymous> g_t6C956B70 = <code>;
<anonymous> g_t6C956BB0 = <code>;
<anonymous> g_t6C956BD0 = <code>;
<anonymous> g_t6C956BF0 = <code>;
<anonymous> g_t6C956C30 = <code>;
<anonymous> g_t6C956C50 = <code>;
<anonymous> g_t6C956C60 = <code>;
<anonymous> g_t6C956CA0 = <code>;
<anonymous> g_t6C956CB0 = <code>;
<anonymous> g_t6C956CC0 = <code>;
<anonymous> g_t6C956D00 = <code>;
<anonymous> g_t6C956D30 = <code>;
<anonymous> g_t6C956D90 = <code>;
<anonymous> g_t6C956DC0 = <code>;
<anonymous> g_t6C956DF0 = <code>;
<anonymous> g_t6C956E10 = <code>;
<anonymous> g_t6C956E40 = <code>;
<anonymous> g_t6C956E80 = <code>;
<anonymous> g_t6C956EC0 = <code>;
<anonymous> g_t6C956EE0 = <code>;
<anonymous> g_t6C956F40 = <code>;
<anonymous> g_t6C956F60 = <code>;
<anonymous> g_t6C956F80 = <code>;
<anonymous> g_t6C956FC0 = <code>;
<anonymous> g_t6C956FE0 = <code>;
<anonymous> g_t6C957000 = <code>;
<anonymous> g_t6C957030 = <code>;
<anonymous> g_t6C957060 = <code>;
<anonymous> g_t6C957080 = <code>;
<anonymous> g_t6C9570A0 = <code>;
<anonymous> g_t6C9570E0 = <code>;
<anonymous> g_t6C957100 = <code>;
<anonymous> g_t6C957120 = <code>;
<anonymous> g_t6C957150 = <code>;
<anonymous> g_t6C957160 = <code>;
<anonymous> g_t6C957180 = <code>;
<anonymous> g_t6C9571E0 = <code>;
<anonymous> g_t6C957200 = <code>;
<anonymous> g_t6C957220 = <code>;
<anonymous> g_t6C957240 = <code>;
<anonymous> g_t6C957260 = <code>;
<anonymous> g_t6C957280 = <code>;
<anonymous> g_t6C9572C0 = <code>;
<anonymous> g_t6C9572E0 = <code>;
<anonymous> g_t6C957300 = <code>;
<anonymous> g_t6C957350 = <code>;
<anonymous> g_t6C957380 = <code>;
<anonymous> g_t6C9573B0 = <code>;
<anonymous> g_t6C9573F0 = <code>;
<anonymous> g_t6C957410 = <code>;
<anonymous> g_t6C957450 = <code>;
<anonymous> g_t6C957480 = <code>;
<anonymous> g_t6C9574A0 = <code>;
<anonymous> g_t6C9574F0 = <code>;
<anonymous> g_t6C957510 = <code>;
<anonymous> g_t6C957550 = <code>;
<anonymous> g_t6C957590 = <code>;
<anonymous> g_t6C9575B0 = <code>;
<anonymous> g_t6C9575D0 = <code>;
<anonymous> g_t6C957610 = <code>;
<anonymous> g_t6C957630 = <code>;
<anonymous> g_t6C957650 = <code>;
<anonymous> g_t6C957690 = <code>;
<anonymous> g_t6C9576C0 = <code>;
<anonymous> g_t6C9576F0 = <code>;
<anonymous> g_t6C957730 = <code>;
<anonymous> g_t6C957750 = <code>;
<anonymous> g_t6C957770 = <code>;
<anonymous> g_t6C9577B0 = <code>;
<anonymous> g_t6C9577D0 = <code>;
<anonymous> g_t6C957800 = <code>;
<anonymous> g_t6C957820 = <code>;
<anonymous> g_t6C957860 = <code>;
<anonymous> g_t6C957880 = <code>;
<anonymous> g_t6C9578E0 = <code>;
<anonymous> g_t6C957900 = <code>;
<anonymous> g_t6C957920 = <code>;
<anonymous> g_t6C957960 = <code>;
<anonymous> g_t6C957990 = <code>;
<anonymous> g_t6C9579B0 = <code>;
<anonymous> g_t6C9579F0 = <code>;
<anonymous> g_t6C957A20 = <code>;
<anonymous> g_t6C957A40 = <code>;
<anonymous> g_t6C957A60 = <code>;
<anonymous> g_t6C957A80 = <code>;
<anonymous> g_t6C957AA0 = <code>;
<anonymous> g_t6C957AE0 = <code>;
<anonymous> g_t6C957B00 = <code>;
<anonymous> g_t6C957B20 = <code>;
<anonymous> g_t6C957B60 = <code>;
<anonymous> g_t6C957B70 = <code>;
<anonymous> g_t6C957B90 = <code>;
<anonymous> g_t6C957BC0 = <code>;
<anonymous> g_t6C957BE0 = <code>;
<anonymous> g_t6C957C00 = <code>;
<anonymous> g_t6C957C40 = <code>;
<anonymous> g_t6C957C60 = <code>;
<anonymous> g_t6C957C80 = <code>;
<anonymous> g_t6C957CC0 = <code>;
<anonymous> g_t6C957CE0 = <code>;
<anonymous> g_t6C957D00 = <code>;
<anonymous> g_t6C957D40 = <code>;
<anonymous> g_t6C957D60 = <code>;
<anonymous> g_t6C957D80 = <code>;
<anonymous> g_t6C957DF0 = <code>;
<anonymous> g_t6C957E10 = <code>;
<anonymous> g_t6C957E20 = <code>;
<anonymous> g_t6C957E40 = <code>;
<anonymous> g_t6C957E50 = <code>;
<anonymous> g_t6C957E60 = <code>;
<anonymous> g_t6C957E80 = <code>;
<anonymous> g_t6C957E90 = <code>;
<anonymous> g_t6C957EA0 = <code>;
<anonymous> g_t6C957EE0 = <code>;
<anonymous> g_t6C957F00 = <code>;
<anonymous> g_t6C957F50 = <code>;
<anonymous> g_t6C957FB0 = <code>;
<anonymous> g_t6C958020 = <code>;
<anonymous> g_t6C958040 = <code>;
<anonymous> g_t6C9580B0 = <code>;
<anonymous> g_t6C9580D0 = <code>;
<anonymous> g_t6C9580F0 = <code>;
<anonymous> g_t6C958150 = <code>;
<anonymous> g_t6C958170 = <code>;
<anonymous> g_t6C958190 = <code>;
<anonymous> g_t6C9581B0 = <code>;
<anonymous> g_t6C9581D0 = <code>;
<anonymous> g_t6C9581F0 = <code>;
<anonymous> g_t6C958210 = <code>;
<anonymous> g_t6C958230 = <code>;
<anonymous> g_t6C958280 = <code>;
<anonymous> g_t6C9582A0 = <code>;
<anonymous> g_t6C9582C0 = <code>;
<anonymous> g_t6C958310 = <code>;
<anonymous> g_t6C958330 = <code>;
<anonymous> g_t6C958360 = <code>;
<anonymous> g_t6C958380 = <code>;
<anonymous> g_t6C9583E0 = <code>;
<anonymous> g_t6C958400 = <code>;
<anonymous> g_t6C958440 = <code>;
<anonymous> g_t6C958460 = <code>;
<anonymous> g_t6C9584B0 = <code>;
<anonymous> g_t6C9587C0 = <code>;
<anonymous> g_t6C958880 = <code>;
<anonymous> g_t6C958A00 = <code>;
<anonymous> g_t6C958AC0 = <code>;
<anonymous> g_t6C958B80 = <code>;
<anonymous> g_t6C958C40 = <code>;
<anonymous> g_t6C958D00 = <code>;
<anonymous> g_t6C958DC0 = <code>;
<anonymous> g_t6C958E80 = <code>;
<anonymous> g_t6C958F40 = <code>;
<anonymous> g_t6C9590C0 = <code>;
<anonymous> g_t6C959180 = <code>;
<anonymous> g_t6C959240 = <code>;
<anonymous> g_t6C959300 = <code>;
<anonymous> g_t6C959480 = <code>;
<anonymous> g_t6C959600 = <code>;
<anonymous> g_t6C9596C0 = <code>;
<anonymous> g_t6C959780 = <code>;
<anonymous> g_t6C959840 = <code>;
<anonymous> g_t6C959900 = <code>;
<anonymous> g_t6C9599C0 = <code>;
<anonymous> g_t6C959B40 = <code>;
<anonymous> g_t6C959CD0 = <code>;
<anonymous> g_t6C959D90 = <code>;
<anonymous> g_t6C959E50 = <code>;
<anonymous> g_t6C959F20 = <code>;
<anonymous> g_t6C95A170 = <code>;
<anonymous> g_t6C95A230 = <code>;
<anonymous> g_t6C95A480 = <code>;
<anonymous> g_t6C95A540 = <code>;
<anonymous> g_t6C95A600 = <code>;
<anonymous> g_t6C95A850 = <code>;
<anonymous> g_t6C95A920 = <code>;
<anonymous> g_t6C95A9F0 = <code>;
<anonymous> g_t6C95AAC0 = <code>;
<anonymous> g_t6C95AB90 = <code>;
<anonymous> g_t6C95AD20 = <code>;
<anonymous> g_t6C95AEA0 = <code>;
<anonymous> g_t6C95B030 = <code>;
<anonymous> g_t6C95B100 = <code>;
<anonymous> g_t6C95B2A0 = <code>;
<anonymous> g_t6C95B360 = <code>;
<anonymous> g_t6C95B430 = <code>;
<anonymous> g_t6C95B4F0 = <code>;
<anonymous> g_t6C95B5C0 = <code>;
<anonymous> g_t6C95B690 = <code>;
<anonymous> g_t6C95B750 = <code>;
<anonymous> g_t6C95B8D0 = <code>;
<anonymous> g_t6C95B990 = <code>;
<anonymous> g_t6C95BB20 = <code>;
<anonymous> g_t6C95BBF0 = <code>;
<anonymous> g_t6C9675F0 = <code>;
ui32 g_dw6CA1F720 = 0xFFFFFFFF;
Eq_441 g_t6CA20180 = 
	{
		;
Eq_441 g_t6CA20190 = 
		{
			;
Eq_441 g_t6CA201A0 = 
			{
				;
<anonymous> * g_ptr6CA201AC = &g_t6C9584B0;
Eq_441 g_t6CA201B0 = 
				{
					;
<anonymous> * g_ptr6CA201B4 = &g_t6C958460;
<anonymous> * g_ptr6CA201B8 = &g_t6C958D00;
<anonymous> * g_ptr6CA201BC = &g_t6C958440;
Eq_441 g_t6CA201C0 = 
					{
						;
<anonymous> * g_ptr6CA201C4 = &g_t6C958400;
<anonymous> * g_ptr6CA201C8 = &g_t6C9583E0;
<anonymous> * g_ptr6CA201CC = &g_t6C959F20;
Eq_441 g_t6CA201D0 = 
						{
							;
<anonymous> * g_ptr6CA201D4 = &g_t6C958DC0;
<anonymous> * g_ptr6CA201D8 = &g_t6C958380;
<anonymous> * g_ptr6CA201DC = &g_t6C958360;
Eq_441 g_t6CA201E0 = 
							{
								;
<anonymous> * g_ptr6CA201E4 = &g_t6C959840;
<anonymous> * g_ptr6CA201E8 = &g_t6C958330;
<anonymous> * g_ptr6CA201EC = &g_t6C958310;
Eq_441 g_t6CA201F0 = 
								{
									;
<anonymous> * g_ptr6CA201F4 = &g_t6C9582C0;
<anonymous> * g_ptr6CA201F8 = &g_t6C9582A0;
<anonymous> * g_ptr6CA201FC = &g_t6C958280;
Eq_441 g_t6CA20200 = 
									{
										;
<anonymous> * g_ptr6CA20204 = &g_t6C958230;
<anonymous> * g_ptr6CA20208 = &g_t6C958210;
<anonymous> * g_ptr6CA2020C = &g_t6C9581F0;
Eq_441 g_t6CA20210 = 
										{
											;
<anonymous> * g_ptr6CA20214 = &g_t6C9581D0;
<anonymous> * g_ptr6CA20218 = &g_t6C9581B0;
<anonymous> * g_ptr6CA2021C = &g_t6C958C40;
Eq_441 g_t6CA20220 = 
											{
												;
<anonymous> * g_ptr6CA20224 = &g_t6C958190;
<anonymous> * g_ptr6CA20228 = &g_t6C958170;
<anonymous> * g_ptr6CA2022C = &g_t6C958150;
Eq_441 g_t6CA20230 = 
												{
													;
<anonymous> * g_ptr6CA20234 = &g_t6C9580F0;
<anonymous> * g_ptr6CA20238 = &g_t6C9580D0;
<anonymous> * g_ptr6CA2023C = &g_t6C9580B0;
Eq_441 g_t6CA20240 = 
													{
														;
<anonymous> * g_ptr6CA20244 = &g_t6C958040;
<anonymous> * g_ptr6CA20248 = &g_t6C958020;
<anonymous> * g_ptr6CA2024C = &g_t6C957FB0;
Eq_441 g_t6CA20250 = 
														{
															;
<anonymous> * g_ptr6CA20254 = &g_t6C957F50;
<anonymous> * g_ptr6CA20258 = &g_t6C957F00;
<anonymous> * g_ptr6CA2025C = &g_t6C959300;
Eq_441 g_t6CA20260 = 
															{
																;
<anonymous> * g_ptr6CA20264 = &g_t6C959600;
<anonymous> * g_ptr6CA20268 = &g_t6C957EE0;
<anonymous> * g_ptr6CA2026C = &g_t6C9599C0;
Eq_441 g_t6CA20270 = 
																{
																	;
<anonymous> * g_ptr6CA20274 = &g_t6C957EA0;
<anonymous> * g_ptr6CA20278 = &g_t6C957E90;
<anonymous> * g_ptr6CA2027C = &g_t6C957E80;
Eq_441 g_t6CA20280 = 
																	{
																		;
<anonymous> * g_ptr6CA20284 = &g_t6C957E60;
<anonymous> * g_ptr6CA20288 = &g_t6C95B690;
<anonymous> * g_ptr6CA2028C = &g_t6C957E50;
Eq_441 g_t6CA20290 = 
																		{
																			;
<anonymous> * g_ptr6CA20294 = &g_t6C957E40;
<anonymous> * g_ptr6CA20298 = &g_t6C95BBF0;
<anonymous> * g_ptr6CA2029C = &g_t6C95B430;
Eq_441 g_t6CA202A0 = 
																			{
																				;
<anonymous> * g_ptr6CA202A4 = &g_t6C957E20;
<anonymous> * g_ptr6CA202A8 = &g_t6C95B8D0;
<anonymous> * g_ptr6CA202AC = &g_t6C957E10;
Eq_441 g_t6CA202B0 = 
																				{
																					;
<anonymous> * g_ptr6CA202B4 = &g_t6C9596C0;
<anonymous> * g_ptr6CA202B8 = &g_t6C957DF0;
<anonymous> * g_ptr6CA202BC = &g_t6C959780;
Eq_441 g_t6CA202C0 = 
																					{
																						;
<anonymous> * g_ptr6CA202C4 = &g_t6C957D80;
<anonymous> * g_ptr6CA202C8 = &g_t6C957D60;
<anonymous> * g_ptr6CA202CC = &g_t6C957D40;
Eq_441 g_t6CA202D0 = 
																						{
																							;
<anonymous> * g_ptr6CA202D4 = &g_t6C957D00;
<anonymous> * g_ptr6CA202D8 = &g_t6C957CE0;
<anonymous> * g_ptr6CA202DC = &g_t6C957CC0;
Eq_441 g_t6CA202E0 = 
																							{
																								;
<anonymous> * g_ptr6CA202E4 = &g_t6C957C80;
<anonymous> * g_ptr6CA202E8 = &g_t6C957C60;
<anonymous> * g_ptr6CA202EC = &g_t6C957C40;
Eq_441 g_t6CA202F0 = 
																								{
																									;
<anonymous> * g_ptr6CA202F4 = &g_t6C957C00;
<anonymous> * g_ptr6CA202F8 = &g_t6C957BE0;
<anonymous> * g_ptr6CA202FC = &g_t6C957BC0;
Eq_441 g_t6CA20300 = 
																									{
																										;
<anonymous> * g_ptr6CA20304 = &g_t6C957B90;
<anonymous> * g_ptr6CA20308 = &g_t6C957B70;
<anonymous> * g_ptr6CA2030C = &g_t6C957B60;
Eq_441 g_t6CA20310 = 
																										{
																											;
<anonymous> * g_ptr6CA20314 = &g_t6C957B20;
<anonymous> * g_ptr6CA20318 = &g_t6C957B00;
<anonymous> * g_ptr6CA2031C = &g_t6C957AE0;
Eq_441 g_t6CA20320 = 
																											{
																												;
<anonymous> * g_ptr6CA20324 = &g_t6C957AA0;
<anonymous> * g_ptr6CA20328 = &g_t6C957A80;
<anonymous> * g_ptr6CA2032C = &g_t6C957A60;
Eq_441 g_t6CA20330 = 
																												{
																													;
<anonymous> * g_ptr6CA20334 = &g_t6C957A40;
<anonymous> * g_ptr6CA20338 = &g_t6C957A20;
<anonymous> * g_ptr6CA2033C = &g_t6C9579F0;
Eq_441 g_t6CA20340 = 
																													{
																														;
<anonymous> * g_ptr6CA20344 = &g_t6C9579B0;
<anonymous> * g_ptr6CA20348 = &g_t6C957990;
<anonymous> * g_ptr6CA2034C = &g_t6C957960;
Eq_441 g_t6CA20350 = 
																														{
																															;
<anonymous> * g_ptr6CA20354 = &g_t6C957920;
<anonymous> * g_ptr6CA20358 = &g_t6C957900;
<anonymous> * g_ptr6CA2035C = &g_t6C9578E0;
Eq_441 g_t6CA20360 = 
																															{
																																;
<anonymous> * g_ptr6CA20364 = &g_t6C957880;
<anonymous> * g_ptr6CA20368 = &g_t6C95B750;
<anonymous> * g_ptr6CA2036C = &g_t6C957860;
Eq_441 g_t6CA20370 = 
																																{
																																	;
<anonymous> * g_ptr6CA20374 = &g_t6C957820;
<anonymous> * g_ptr6CA20378 = &g_t6C957800;
<anonymous> * g_ptr6CA2037C = &g_t6C95B990;
Eq_441 g_t6CA20380 = 
																																	{
																																		;
<anonymous> * g_ptr6CA20384 = &g_t6C9577D0;
<anonymous> * g_ptr6CA20388 = &g_t6C9577B0;
<anonymous> * g_ptr6CA2038C = &g_t6C95BB20;
Eq_441 g_t6CA20390 = 
																																		{
																																			;
<anonymous> * g_ptr6CA20394 = &g_t6C957770;
<anonymous> * g_ptr6CA20398 = &g_t6C957750;
<anonymous> * g_ptr6CA2039C = &g_t6C957730;
Eq_441 g_t6CA203A0 = 
																																			{
																																				;
<anonymous> * g_ptr6CA203A4 = &g_t6C9576F0;
<anonymous> * g_ptr6CA203A8 = &g_t6C9576C0;
<anonymous> * g_ptr6CA203AC = &g_t6C957690;
Eq_441 g_t6CA203B0 = 
																																				{
																																					;
<anonymous> * g_ptr6CA203B4 = &g_t6C957650;
<anonymous> * g_ptr6CA203B8 = &g_t6C957630;
<anonymous> * g_ptr6CA203BC = &g_t6C957610;
Eq_441 g_t6CA203C0 = 
																																					{
																																						;
<anonymous> * g_ptr6CA203C4 = &g_t6C9575D0;
<anonymous> * g_ptr6CA203C8 = &g_t6C9575B0;
<anonymous> * g_ptr6CA203CC = &g_t6C957590;
Eq_441 g_t6CA203D0 = 
																																						{
																																							;
<anonymous> * g_ptr6CA203D4 = &g_t6C957550;
<anonymous> * g_ptr6CA203D8 = &g_t6C957510;
<anonymous> * g_ptr6CA203DC = &g_t6C9574F0;
Eq_441 g_t6CA203E0 = 
																																							{
																																								;
<anonymous> * g_ptr6CA203E4 = &g_t6C9574A0;
<anonymous> * g_ptr6CA203E8 = &g_t6C957480;
<anonymous> * g_ptr6CA203EC = &g_t6C957450;
Eq_441 g_t6CA203F0 = 
																																								{
																																									;
<anonymous> * g_ptr6CA203F4 = &g_t6C959480;
<anonymous> * g_ptr6CA203F8 = &g_t6C957410;
<anonymous> * g_ptr6CA203FC = &g_t6C9573F0;
Eq_441 g_t6CA20400 = 
																																									{
																																										;
<anonymous> * g_ptr6CA20404 = &g_t6C9573B0;
<anonymous> * g_ptr6CA20408 = &g_t6C957380;
<anonymous> * g_ptr6CA2040C = &g_t6C957350;
Eq_441 g_t6CA20410 = 
																																										{
																																											;
<anonymous> * g_ptr6CA20414 = &g_t6C957300;
<anonymous> * g_ptr6CA20418 = &g_t6C9572E0;
<anonymous> * g_ptr6CA2041C = &g_t6C9572C0;
Eq_441 g_t6CA20420 = 
																																											{
																																												;
<anonymous> * g_ptr6CA20424 = &g_t6C957280;
<anonymous> * g_ptr6CA20428 = &g_t6C957260;
<anonymous> * g_ptr6CA2042C = &g_t6C957240;
Eq_441 g_t6CA20430 = 
																																												{
																																													;
<anonymous> * g_ptr6CA20434 = &g_t6C957220;
<anonymous> * g_ptr6CA20438 = &g_t6C957200;
<anonymous> * g_ptr6CA2043C = &g_t6C9571E0;
Eq_441 g_t6CA20440 = 
																																													{
																																														;
<anonymous> * g_ptr6CA20444 = &g_t6C957180;
<anonymous> * g_ptr6CA20448 = &g_t6C957160;
<anonymous> * g_ptr6CA2044C = &g_t6C957150;
Eq_441 g_t6CA20450 = 
																																														{
																																															;
<anonymous> * g_ptr6CA20454 = &g_t6C957120;
<anonymous> * g_ptr6CA20458 = &g_t6C957100;
<anonymous> * g_ptr6CA2045C = &g_t6C9570E0;
Eq_441 g_t6CA20460 = 
																																															{
																																																;
<anonymous> * g_ptr6CA20464 = &g_t6C9570A0;
<anonymous> * g_ptr6CA20468 = &g_t6C957080;
<anonymous> * g_ptr6CA2046C = &g_t6C957060;
Eq_441 g_t6CA20470 = 
																																																{
																																																	;
<anonymous> * g_ptr6CA20474 = &g_t6C958B80;
<anonymous> * g_ptr6CA20478 = &g_t6C957030;
<anonymous> * g_ptr6CA2047C = &g_t6C958A00;
Eq_441 g_t6CA20480 = 
																																																	{
																																																		;
<anonymous> * g_ptr6CA20484 = &g_t6C957000;
<anonymous> * g_ptr6CA20488 = &g_t6C956FE0;
<anonymous> * g_ptr6CA2048C = &g_t6C956FC0;
Eq_441 g_t6CA20490 = 
																																																		{
																																																			;
<anonymous> * g_ptr6CA20494 = &g_t6C956F80;
<anonymous> * g_ptr6CA20498 = &g_t6C956F60;
<anonymous> * g_ptr6CA2049C = &g_t6C956F40;
Eq_441 g_t6CA204A0 = 
																																																			{
																																																				;
<anonymous> * g_ptr6CA204A4 = &g_t6C9590C0;
<anonymous> * g_ptr6CA204A8 = &g_t6C956EE0;
<anonymous> * g_ptr6CA204AC = &g_t6C956EC0;
Eq_441 g_t6CA204B0 = 
																																																				{
																																																					;
<anonymous> * g_ptr6CA204B4 = &g_t6C958E80;
<anonymous> * g_ptr6CA204B8 = &g_t6C956E80;
<anonymous> * g_ptr6CA204BC = &g_t6C956E40;
Eq_441 g_t6CA204C0 = 
																																																					{
																																																						;
<anonymous> * g_ptr6CA204C4 = &g_t6C956E10;
<anonymous> * g_ptr6CA204C8 = &g_t6C956DF0;
<anonymous> * g_ptr6CA204CC = &g_t6C956DC0;
Eq_441 g_t6CA204D0 = 
																																																						{
																																																							;
<anonymous> * g_ptr6CA204D4 = &g_t6C956D90;
<anonymous> * g_ptr6CA204D8 = &g_t6C956D30;
<anonymous> * g_ptr6CA204DC = &g_t6C956D00;
Eq_441 g_t6CA204E0 = 
																																																							{
																																																								;
<anonymous> * g_ptr6CA204E4 = &g_t6C956CC0;
<anonymous> * g_ptr6CA204E8 = &g_t6C956CB0;
<anonymous> * g_ptr6CA204EC = &g_t6C956CA0;
Eq_441 g_t6CA204F0 = 
																																																								{
																																																									;
<anonymous> * g_ptr6CA204F4 = &g_t6C956C60;
<anonymous> * g_ptr6CA204F8 = &g_t6C956C50;
<anonymous> * g_ptr6CA204FC = &g_t6C956C30;
Eq_441 g_t6CA20500 = 
																																																									{
																																																										;
<anonymous> * g_ptr6CA20504 = &g_t6C956BF0;
<anonymous> * g_ptr6CA20508 = &g_t6C956BD0;
<anonymous> * g_ptr6CA2050C = &g_t6C956BB0;
Eq_441 g_t6CA20510 = 
																																																										{
																																																											;
<anonymous> * g_ptr6CA20514 = &g_t6C956B70;
<anonymous> * g_ptr6CA20518 = &g_t6C956B50;
<anonymous> * g_ptr6CA2051C = &g_t6C956B30;
Eq_441 g_t6CA20520 = 
																																																											{
																																																												;
<anonymous> * g_ptr6CA20524 = &g_t6C956AF0;
<anonymous> * g_ptr6CA20528 = &g_t6C956AE0;
<anonymous> * g_ptr6CA2052C = &g_t6C956AC0;
Eq_441 g_t6CA20530 = 
																																																												{
																																																													;
<anonymous> * g_ptr6CA20534 = &g_t6C956A80;
<anonymous> * g_ptr6CA20538 = &g_t6C956A60;
<anonymous> * g_ptr6CA2053C = &g_t6C956A30;
Eq_441 g_t6CA20540 = 
																																																													{
																																																														;
<anonymous> * g_ptr6CA20544 = &g_t6C9569B0;
<anonymous> * g_ptr6CA20548 = &g_t6C956960;
<anonymous> * g_ptr6CA2054C = &g_t6C956940;
Eq_441 g_t6CA20550 = 
																																																														{
																																																															;
<anonymous> * g_ptr6CA20554 = &g_t6C956900;
<anonymous> * g_ptr6CA20558 = &g_t6C9568E0;
<anonymous> * g_ptr6CA2055C = &g_t6C9568A0;
Eq_441 g_t6CA20560 = 
																																																															{
																																																																;
<anonymous> * g_ptr6CA20564 = &g_t6C956840;
<anonymous> * g_ptr6CA20568 = &g_t6C9567E0;
<anonymous> * g_ptr6CA2056C = &g_t6C956790;
Eq_441 g_t6CA20570 = 
																																																																{
																																																																	;
<anonymous> * g_ptr6CA20574 = &g_t6C956700;
<anonymous> * g_ptr6CA20578 = &g_t6C9566F0;
<anonymous> * g_ptr6CA2057C = &g_t6C9566D0;
Eq_441 g_t6CA20580 = 
																																																																	{
																																																																		;
<anonymous> * g_ptr6CA20584 = &g_t6C956680;
<anonymous> * g_ptr6CA20588 = &g_t6C956650;
<anonymous> * g_ptr6CA2058C = &g_t6C956610;
Eq_441 g_t6CA20590 = 
																																																																		{
																																																																			;
<anonymous> * g_ptr6CA20594 = &g_t6C9565B0;
<anonymous> * g_ptr6CA20598 = &g_t6C956590;
<anonymous> * g_ptr6CA2059C = &g_t6C956540;
Eq_441 g_t6CA205A0 = 
																																																																			{
																																																																				;
<anonymous> * g_ptr6CA205A4 = &g_t6C9564F0;
<anonymous> * g_ptr6CA205A8 = &g_t6C9564D0;
<anonymous> * g_ptr6CA205AC = &g_t6C9564B0;
Eq_441 g_t6CA205B0 = 
																																																																				{
																																																																					;
<anonymous> * g_ptr6CA205B4 = &g_t6C956430;
<anonymous> * g_ptr6CA205B8 = &g_t6C956410;
<anonymous> * g_ptr6CA205BC = &g_t6C9563C0;
Eq_441 g_t6CA205C0 = 
																																																																					{
																																																																						;
<anonymous> * g_ptr6CA205C4 = &g_t6C956340;
<anonymous> * g_ptr6CA205C8 = &g_t6C956310;
<anonymous> * g_ptr6CA205CC = &g_t6C9562F0;
Eq_441 g_t6CA205D0 = 
																																																																						{
																																																																							;
<anonymous> * g_ptr6CA205D4 = &g_t6C9562B0;
<anonymous> * g_ptr6CA205D8 = &g_t6C956270;
<anonymous> * g_ptr6CA205DC = &g_t6C9561F0;
Eq_441 g_t6CA205E0 = 
																																																																							{
																																																																								;
<anonymous> * g_ptr6CA205E4 = &g_t6C956190;
<anonymous> * g_ptr6CA205E8 = &g_t6C956170;
<anonymous> * g_ptr6CA205EC = &g_t6C956150;
Eq_441 g_t6CA205F0 = 
																																																																								{
																																																																									;
<anonymous> * g_ptr6CA205F4 = &g_t6C956100;
<anonymous> * g_ptr6CA205F8 = &g_t6C9560D0;
<anonymous> * g_ptr6CA205FC = &g_t6C9560B0;
Eq_441 g_t6CA20600 = 
																																																																									{
																																																																										;
<anonymous> * g_ptr6CA20604 = &g_t6C956070;
<anonymous> * g_ptr6CA20608 = &g_t6C956050;
<anonymous> * g_ptr6CA2060C = &g_t6C956010;
Eq_441 g_t6CA20610 = 
																																																																										{
																																																																											;
<anonymous> * g_ptr6CA20614 = &g_t6C955F80;
<anonymous> * g_ptr6CA20618 = &g_t6C955F30;
<anonymous> * g_ptr6CA2061C = &g_t6C955F10;
Eq_441 g_t6CA20620 = 
																																																																											{
																																																																												;
<anonymous> * g_ptr6CA20624 = &g_t6C955ED0;
<anonymous> * g_ptr6CA20628 = &g_t6C955EA0;
<anonymous> * g_ptr6CA2062C = &g_t6C955E70;
Eq_441 g_t6CA20630 = 
																																																																												{
																																																																													;
<anonymous> * g_ptr6CA20634 = &g_t6C955DF0;
<anonymous> * g_ptr6CA20638 = &g_t6C955DD0;
<anonymous> * g_ptr6CA2063C = &g_t6C955DA0;
Eq_441 g_t6CA20640 = 
																																																																													{
																																																																														;
<anonymous> * g_ptr6CA20644 = &g_t6C955D50;
<anonymous> * g_ptr6CA20648 = &g_t6C955D10;
<anonymous> * g_ptr6CA2064C = &g_t6C955CA0;
Eq_441 g_t6CA20650 = 
																																																																														{
																																																																															;
<anonymous> * g_ptr6CA20654 = &g_t6C95B5C0;
<anonymous> * g_ptr6CA20658 = &g_t6C95B100;
<anonymous> * g_ptr6CA2065C = &g_t6C95AEA0;
Eq_441 g_t6CA20660 = 
																																																																															{
																																																																																;
<anonymous> * g_ptr6CA20664 = &g_t6C955C00;
<anonymous> * g_ptr6CA20668 = &g_t6C955BE0;
<anonymous> * g_ptr6CA2066C = &g_t6C955BC0;
Eq_441 g_t6CA20670 = 
																																																																																{
																																																																																	;
<anonymous> * g_ptr6CA20674 = &g_t6C95B2A0;
<anonymous> * g_ptr6CA20678 = &g_t6C95B360;
<anonymous> * g_ptr6CA2067C = &g_t6C955B80;
Eq_441 g_t6CA20680 = 
																																																																																	{
																																																																																		;
<anonymous> * g_ptr6CA20684 = &g_t6C955B40;
<anonymous> * g_ptr6CA20688 = &g_t6C955B20;
<anonymous> * g_ptr6CA2068C = &g_t6C955B00;
Eq_441 g_t6CA20690 = 
																																																																																		{
																																																																																			;
<anonymous> * g_ptr6CA20694 = &g_t6C955AC0;
<anonymous> * g_ptr6CA20698 = &g_t6C955A90;
<anonymous> * g_ptr6CA2069C = &g_t6C955A60;
Eq_441 g_t6CA206A0 = 
																																																																																			{
																																																																																				;
<anonymous> * g_ptr6CA206A4 = &g_t6C955A10;
<anonymous> * g_ptr6CA206A8 = &g_t6C9559F0;
<anonymous> * g_ptr6CA206AC = &g_t6C9559C0;
Eq_441 g_t6CA206B0 = 
																																																																																				{
																																																																																					;
<anonymous> * g_ptr6CA206B4 = &g_t6C955930;
<anonymous> * g_ptr6CA206B8 = &g_t6C955910;
<anonymous> * g_ptr6CA206BC = &g_t6C9558E0;
Eq_441 g_t6CA206C0 = 
																																																																																					{
																																																																																						;
<anonymous> * g_ptr6CA206C4 = &g_t6C9558A0;
<anonymous> * g_ptr6CA206C8 = &g_t6C955880;
<anonymous> * g_ptr6CA206CC = &g_t6C955860;
Eq_441 g_t6CA206D0 = 
																																																																																						{
																																																																																							;
<anonymous> * g_ptr6CA206D4 = &g_t6C955840;
<anonymous> * g_ptr6CA206D8 = &g_t6C955810;
<anonymous> * g_ptr6CA206DC = &g_t6C9557D0;
Eq_441 g_t6CA206E0 = 
																																																																																							{
																																																																																								;
<anonymous> * g_ptr6CA206E4 = &g_t6C955790;
<anonymous> * g_ptr6CA206E8 = &g_t6C955770;
<anonymous> * g_ptr6CA206EC = &g_t6C955750;
Eq_441 g_t6CA206F0 = 
																																																																																								{
																																																																																									;
<anonymous> * g_ptr6CA206F4 = &g_t6C955700;
<anonymous> * g_ptr6CA206F8 = &g_t6C9556D0;
<anonymous> * g_ptr6CA206FC = &g_t6C9556A0;
Eq_441 g_t6CA20700 = 
																																																																																									{
																																																																																										;
<anonymous> * g_ptr6CA20704 = &g_t6C955650;
<anonymous> * g_ptr6CA20708 = &g_t6C955620;
<anonymous> * g_ptr6CA2070C = &g_t6C9555F0;
Eq_441 g_t6CA20710 = 
																																																																																										{
																																																																																											;
<anonymous> * g_ptr6CA20714 = &g_t6C9555A0;
<anonymous> * g_ptr6CA20718 = &g_t6C955570;
<anonymous> * g_ptr6CA2071C = &g_t6C955540;
Eq_441 g_t6CA20720 = 
																																																																																											{
																																																																																												;
<anonymous> * g_ptr6CA20724 = &g_t6C955500;
<anonymous> * g_ptr6CA20728 = &g_t6C9554E0;
<anonymous> * g_ptr6CA2072C = &g_t6C9554C0;
Eq_441 g_t6CA20730 = 
																																																																																												{
																																																																																													;
<anonymous> * g_ptr6CA20734 = &g_t6C955480;
<anonymous> * g_ptr6CA20738 = &g_t6C955460;
<anonymous> * g_ptr6CA2073C = &g_t6C955430;
Eq_441 g_t6CA20740 = 
																																																																																													{
																																																																																														;
<anonymous> * g_ptr6CA20744 = &g_t6C9553D0;
<anonymous> * g_ptr6CA20748 = &g_t6C9553A0;
<anonymous> * g_ptr6CA2074C = &g_t6C955360;
Eq_441 g_t6CA20750 = 
																																																																																														{
																																																																																															;
<anonymous> * g_ptr6CA20754 = &g_t6C955300;
<anonymous> * g_ptr6CA20758 = &g_t6C9552E0;
<anonymous> * g_ptr6CA2075C = &g_t6C9552B0;
Eq_441 g_t6CA20760 = 
																																																																																															{
																																																																																																;
<anonymous> * g_ptr6CA20764 = &g_t6C955250;
<anonymous> * g_ptr6CA20768 = &g_t6C955220;
<anonymous> * g_ptr6CA2076C = &g_t6C9551F0;
Eq_441 g_t6CA20770 = 
																																																																																																{
																																																																																																	;
<anonymous> * g_ptr6CA20774 = &g_t6C9551A0;
<anonymous> * g_ptr6CA20778 = &g_t6C955180;
<anonymous> * g_ptr6CA2077C = &g_t6C955150;
Eq_441 g_t6CA20780 = 
																																																																																																	{
																																																																																																		;
<anonymous> * g_ptr6CA20784 = &g_t6C9550E0;
<anonymous> * g_ptr6CA20788 = &g_t6C9550B0;
<anonymous> * g_ptr6CA2078C = &g_t6C955080;
Eq_441 g_t6CA20790 = 
																																																																																																		{
																																																																																																			;
<anonymous> * g_ptr6CA20794 = &g_t6C955020;
<anonymous> * g_ptr6CA20798 = &g_t6C954FF0;
<anonymous> * g_ptr6CA2079C = &g_t6C954FC0;
Eq_441 g_t6CA207A0 = 
																																																																																																			{
																																																																																																				;
<anonymous> * g_ptr6CA207A4 = &g_t6C954F70;
<anonymous> * g_ptr6CA207A8 = &g_t6C954F40;
<anonymous> * g_ptr6CA207AC = &g_t6C954F10;
Eq_441 g_t6CA207B0 = 
																																																																																																				{
																																																																																																					;
<anonymous> * g_ptr6CA207B4 = &g_t6C954EB0;
<anonymous> * g_ptr6CA207B8 = &g_t6C954E80;
<anonymous> * g_ptr6CA207BC = &g_t6C954E60;
Eq_441 g_t6CA207C0 = 
																																																																																																					{
																																																																																																						;
<anonymous> * g_ptr6CA207C4 = &g_t6C954E10;
<anonymous> * g_ptr6CA207C8 = &g_t6C954DF0;
<anonymous> * g_ptr6CA207CC = &g_t6C954DA0;
Eq_441 g_t6CA207D0 = Recursion too deep;
<anonymous> * g_ptr6CA207D4 = &g_t6C954CE0;
<anonymous> * g_ptr6CA207D8 = &g_t6C954C50;
<anonymous> * g_ptr6CA207DC = &g_t6C95B4F0;
Eq_441 g_t6CA207E0 = Recursion too deep;
<anonymous> * g_ptr6CA207E4 = &g_t6C954C10;
<anonymous> * g_ptr6CA207E8 = &g_t6C95B030;
<anonymous> * g_ptr6CA207EC = &g_t6C954BF0;
Eq_441 g_t6CA207F0 = Recursion too deep;
<anonymous> * g_ptr6CA207F4 = &g_t6C954BA0;
<anonymous> * g_ptr6CA207F8 = &g_t6C954B70;
<anonymous> * g_ptr6CA207FC = &g_t6C954B50;
Eq_441 g_t6CA20800 = Recursion too deep;
<anonymous> * g_ptr6CA20804 = &g_t6C954AD0;
<anonymous> * g_ptr6CA20808 = &g_t6C954AA0;
<anonymous> * g_ptr6CA2080C = &g_t6C954A80;
Eq_441 g_t6CA20810 = Recursion too deep;
<anonymous> * g_ptr6CA20814 = &g_t6C954A40;
<anonymous> * g_ptr6CA20818 = &g_t6C954A20;
<anonymous> * g_ptr6CA2081C = &g_t6C954A00;
Eq_441 g_t6CA20820 = Recursion too deep;
<anonymous> * g_ptr6CA20824 = &g_t6C9549A0;
<anonymous> * g_ptr6CA20828 = &g_t6C954920;
<anonymous> * g_ptr6CA2082C = &g_t6C9548F0;
Eq_441 g_t6CA20830 = Recursion too deep;
<anonymous> * g_ptr6CA20834 = &g_t6C954870;
<anonymous> * g_ptr6CA20838 = &g_t6C954830;
<anonymous> * g_ptr6CA2083C = &g_t6C9547F0;
Eq_441 g_t6CA20840 = Recursion too deep;
<anonymous> * g_ptr6CA20844 = &g_t6C954770;
<anonymous> * g_ptr6CA20848 = &g_t6C954750;
<anonymous> * g_ptr6CA2084C = &g_t6C954730;
Eq_441 g_t6CA20850 = Recursion too deep;
<anonymous> * g_ptr6CA20854 = &g_t6C954710;
<anonymous> * g_ptr6CA20858 = &g_t6C9546F0;
<anonymous> * g_ptr6CA2085C = &g_t6C9546D0;
Eq_441 g_t6CA20860 = Recursion too deep;
<anonymous> * g_ptr6CA20864 = &g_t6C9546C0;
<anonymous> * g_ptr6CA20868 = &g_t6C9546A0;
<anonymous> * g_ptr6CA2086C = &g_t6C954670;
Eq_441 g_t6CA20870 = Recursion too deep;
<anonymous> * g_ptr6CA20874 = &g_t6C954650;
<anonymous> * g_ptr6CA20878 = &g_t6C954640;
<anonymous> * g_ptr6CA2087C = &g_t6C954620;
Eq_441 g_t6CA20880 = Recursion too deep;
<anonymous> * g_ptr6CA20884 = &g_t6C9545D0;
<anonymous> * g_ptr6CA20888 = &g_t6C95AB90;
<anonymous> * g_ptr6CA2088C = &g_t6C9545B0;
Eq_441 g_t6CA20890 = Recursion too deep;
<anonymous> * g_ptr6CA20894 = &g_t6C954560;
<anonymous> * g_ptr6CA20898 = &g_t6C954540;
<anonymous> * g_ptr6CA2089C = &g_t6C954530;
Eq_441 g_t6CA208A0 = Recursion too deep;
<anonymous> * g_ptr6CA208A4 = &g_t6C954510;
<anonymous> * g_ptr6CA208A8 = &g_t6C9544F0;
<anonymous> * g_ptr6CA208AC = &g_t6C9544D0;
Eq_441 g_t6CA208B0 = Recursion too deep;
<anonymous> * g_ptr6CA208B4 = &g_t6C9544C0;
<anonymous> * g_ptr6CA208B8 = &g_t6C9544B0;
<anonymous> * g_ptr6CA208BC = &g_t6C954490;
Eq_441 g_t6CA208C0 = Recursion too deep;
<anonymous> * g_ptr6CA208C4 = &g_t6C954450;
<anonymous> * g_ptr6CA208C8 = &g_t6C954420;
<anonymous> * g_ptr6CA208CC = &g_t6C954400;
Eq_441 g_t6CA208D0 = Recursion too deep;
<anonymous> * g_ptr6CA208D4 = &g_t6C9543B0;
<anonymous> * g_ptr6CA208D8 = &g_t6C954390;
<anonymous> * g_ptr6CA208DC = &g_t6C954370;
Eq_441 g_t6CA208E0 = Recursion too deep;
<anonymous> * g_ptr6CA208E4 = &g_t6C954330;
<anonymous> * g_ptr6CA208E8 = &g_t6C9542D0;
<anonymous> * g_ptr6CA208EC = &g_t6C9542B0;
Eq_441 g_t6CA208F0 = Recursion too deep;
<anonymous> * g_ptr6CA208F4 = &g_t6C954270;
<anonymous> * g_ptr6CA208F8 = &g_t6C954250;
<anonymous> * g_ptr6CA208FC = &g_t6C954230;
Eq_441 g_t6CA20900 = Recursion too deep;
<anonymous> * g_ptr6CA20904 = &g_t6C9541F0;
<anonymous> * g_ptr6CA20908 = &g_t6C9541C0;
<anonymous> * g_ptr6CA2090C = &g_t6C9541A0;
Eq_441 g_t6CA20910 = Recursion too deep;
<anonymous> * g_ptr6CA20914 = &g_t6C954140;
<anonymous> * g_ptr6CA20918 = &g_t6C954110;
<anonymous> * g_ptr6CA2091C = &g_t6C9540E0;
Eq_441 g_t6CA20920 = Recursion too deep;
<anonymous> * g_ptr6CA20924 = &g_t6C954080;
<anonymous> * g_ptr6CA20928 = &g_t6C954050;
<anonymous> * g_ptr6CA2092C = &g_t6C954020;
Eq_441 g_t6CA20930 = Recursion too deep;
<anonymous> * g_ptr6CA20934 = &g_t6C95AAC0;
<anonymous> * g_ptr6CA20938 = &g_t6C95A850;
<anonymous> * g_ptr6CA2093C = &g_t6C95A920;
Eq_441 g_t6CA20940 = Recursion too deep;
<anonymous> * g_ptr6CA20944 = &g_t6C953FE0;
<anonymous> * g_ptr6CA20948 = &g_t6C953FC0;
<anonymous> * g_ptr6CA2094C = &g_t6C953FA0;
Eq_441 g_t6CA20950 = Recursion too deep;
<anonymous> * g_ptr6CA20954 = &g_t6C953F60;
<anonymous> * g_ptr6CA20958 = &g_t6C953F30;
<anonymous> * g_ptr6CA2095C = &g_t6C953F10;
Eq_441 g_t6CA20960 = Recursion too deep;
<anonymous> * g_ptr6CA20964 = &g_t6C953EC0;
<anonymous> * g_ptr6CA20968 = &g_t6C953EA0;
<anonymous> * g_ptr6CA2096C = &g_t6C953E60;
Eq_441 g_t6CA20970 = Recursion too deep;
<anonymous> * g_ptr6CA20974 = &g_t6C95A9F0;
<anonymous> * g_ptr6CA20978 = &g_t6C953E10;
<anonymous> * g_ptr6CA2097C = &g_t6C959B40;
Eq_441 g_t6CA20980 = Recursion too deep;
<anonymous> * g_ptr6CA20984 = &g_t6C953DF0;
<anonymous> * g_ptr6CA20988 = &g_t6C953DD0;
<anonymous> * g_ptr6CA2098C = &g_t6C959180;
Eq_441 g_t6CA20990 = Recursion too deep;
<anonymous> * g_ptr6CA20994 = &g_t6C953D90;
<anonymous> * g_ptr6CA20998 = &g_t6C953D70;
<anonymous> * g_ptr6CA2099C = &g_t6C953D50;
Eq_441 g_t6CA209A0 = Recursion too deep;
<anonymous> * g_ptr6CA209A4 = &g_t6C95A480;
<anonymous> * g_ptr6CA209A8 = &g_t6C953D20;
<anonymous> * g_ptr6CA209AC = &g_t6C953CF0;
Eq_441 g_t6CA209B0 = Recursion too deep;
<anonymous> * g_ptr6CA209B4 = &g_t6C953CC0;
<anonymous> * g_ptr6CA209B8 = &g_t6C953CA0;
<anonymous> * g_ptr6CA209BC = &g_t6C953C80;
Eq_441 g_t6CA209C0 = Recursion too deep;
<anonymous> * g_ptr6CA209C4 = &g_t6C953C30;
<anonymous> * g_ptr6CA209C8 = &g_t6C959240;
<anonymous> * g_ptr6CA209CC = &g_t6C953C20;
Eq_441 g_t6CA209D0 = Recursion too deep;
<anonymous> * g_ptr6CA209D4 = &g_t6C953BF0;
<anonymous> * g_ptr6CA209D8 = &g_t6C953BC0;
<anonymous> * g_ptr6CA209DC = &g_t6C953BA0;
Eq_441 g_t6CA209E0 = Recursion too deep;
<anonymous> * g_ptr6CA209E4 = &g_t6C953B60;
<anonymous> * g_ptr6CA209E8 = &g_t6C953B30;
<anonymous> * g_ptr6CA209EC = &g_t6C953B10;
Eq_441 g_t6CA209F0 = Recursion too deep;
<anonymous> * g_ptr6CA209F4 = &g_t6C953AC0;
<anonymous> * g_ptr6CA209F8 = &g_t6C953AA0;
<anonymous> * g_ptr6CA209FC = &g_t6C95A540;
Eq_441 g_t6CA20A00 = Recursion too deep;
<anonymous> * g_ptr6CA20A04 = &g_t6C953A50;
<anonymous> * g_ptr6CA20A08 = &g_t6C95A230;
<anonymous> * g_ptr6CA20A0C = &g_t6C95A600;
Eq_441 g_t6CA20A10 = Recursion too deep;
<anonymous> * g_ptr6CA20A14 = &g_t6C9539F0;
<anonymous> * g_ptr6CA20A18 = &g_t6C9539D0;
<anonymous> * g_ptr6CA20A1C = &g_t6C9539B0;
Eq_441 g_t6CA20A20 = Recursion too deep;
<anonymous> * g_ptr6CA20A24 = &g_t6C953970;
<anonymous> * g_ptr6CA20A28 = &g_t6C953920;
<anonymous> * g_ptr6CA20A2C = &g_t6C9538F0;
Eq_441 g_t6CA20A30 = Recursion too deep;
<anonymous> * g_ptr6CA20A34 = &g_t6C9538B0;
<anonymous> * g_ptr6CA20A38 = &g_t6C953890;
<anonymous> * g_ptr6CA20A3C = &g_t6C953870;
Eq_441 g_t6CA20A40 = Recursion too deep;
<anonymous> * g_ptr6CA20A44 = &g_t6C953820;
<anonymous> * g_ptr6CA20A48 = &g_t6C953800;
<anonymous> * g_ptr6CA20A4C = &g_t6C9537B0;
Eq_441 g_t6CA20A50 = Recursion too deep;
<anonymous> * g_ptr6CA20A54 = &g_t6C953730;
<anonymous> * g_ptr6CA20A58 = &g_t6C953710;
<anonymous> * g_ptr6CA20A5C = &g_t6C9536F0;
Eq_441 g_t6CA20A60 = Recursion too deep;
<anonymous> * g_ptr6CA20A64 = &g_t6C9536B0;
<anonymous> * g_ptr6CA20A68 = &g_t6C953690;
<anonymous> * g_ptr6CA20A6C = &g_t6C953670;
Eq_441 g_t6CA20A70 = Recursion too deep;
<anonymous> * g_ptr6CA20A74 = &g_t6C953630;
<anonymous> * g_ptr6CA20A78 = &g_t6C953610;
<anonymous> * g_ptr6CA20A7C = &g_t6C95AD20;
Eq_441 g_t6CA20A80 = Recursion too deep;
<anonymous> * g_ptr6CA20A84 = &g_t6C9535F0;
<anonymous> * g_ptr6CA20A88 = &g_t6C9535C0;
<anonymous> * g_ptr6CA20A8C = &g_t6C9535A0;
Eq_441 g_t6CA20A90 = Recursion too deep;
<anonymous> * g_ptr6CA20A94 = &g_t6C959900;
<anonymous> * g_ptr6CA20A98 = &g_t6C9587C0;
<anonymous> * g_ptr6CA20A9C = &g_t6C953560;
Eq_441 g_t6CA20AA0 = Recursion too deep;
<anonymous> * g_ptr6CA20AA4 = &g_t6C953510;
<anonymous> * g_ptr6CA20AA8 = &g_t6C9534F0;
<anonymous> * g_ptr6CA20AAC = &g_t6C953490;
Eq_441 g_t6CA20AB0 = Recursion too deep;
<anonymous> * g_ptr6CA20AB4 = &g_t6C953450;
<anonymous> * g_ptr6CA20AB8 = &g_t6C959CD0;
<anonymous> * g_ptr6CA20ABC = &g_t6C958880;
Eq_441 g_t6CA20AC0 = Recursion too deep;
<anonymous> * g_ptr6CA20AC4 = &g_t6C9533F0;
<anonymous> * g_ptr6CA20AC8 = &g_t6C9533C0;
<anonymous> * g_ptr6CA20ACC = &g_t6C958AC0;
Eq_441 g_t6CA20AD0 = Recursion too deep;
<anonymous> * g_ptr6CA20AD4 = &g_t6C953380;
<anonymous> * g_ptr6CA20AD8 = &g_t6C953340;
<anonymous> * g_ptr6CA20ADC = &g_t6C953330;
Eq_441 g_t6CA20AE0 = Recursion too deep;
<anonymous> * g_ptr6CA20AE4 = &g_t6C9532A0;
<anonymous> * g_ptr6CA20AE8 = &g_t6C953270;
<anonymous> * g_ptr6CA20AEC = &g_t6C959E50;
Eq_441 g_t6CA20AF0 = Recursion too deep;
<anonymous> * g_ptr6CA20AF4 = &g_t6C953230;
<anonymous> * g_ptr6CA20AF8 = &g_t6C953210;
<anonymous> * g_ptr6CA20AFC = &g_t6C9531F0;
Eq_441 g_t6CA20B00 = Recursion too deep;
<anonymous> * g_ptr6CA20B04 = &g_t6C9531B0;
<anonymous> * g_ptr6CA20B08 = &g_t6C953180;
<anonymous> * g_ptr6CA20B0C = &g_t6C953160;
Eq_441 g_t6CA20B10 = Recursion too deep;
<anonymous> * g_ptr6CA20B14 = &g_t6C953110;
<anonymous> * g_ptr6CA20B18 = &g_t6C9530F0;
<anonymous> * g_ptr6CA20B1C = &g_t6C9530D0;
Eq_441 g_t6CA20B20 = Recursion too deep;
<anonymous> * g_ptr6CA20B24 = &g_t6C953070;
<anonymous> * g_ptr6CA20B28 = &g_t6C953040;
<anonymous> * g_ptr6CA20B2C = &g_t6C953010;
Eq_441 g_t6CA20B30 = Recursion too deep;
<anonymous> * g_ptr6CA20B34 = &g_t6C959D90;
<anonymous> * g_ptr6CA20B38 = &g_t6C952FF0;
<anonymous> * g_ptr6CA20B3C = &g_t6C952FD0;
Eq_441 g_t6CA20B40 = Recursion too deep;
<anonymous> * g_ptr6CA20B44 = &g_t6C952F80;
<anonymous> * g_ptr6CA20B48 = &g_t6C952F60;
<anonymous> * g_ptr6CA20B4C = &g_t6C952F40;
Eq_441 g_t6CA20B50 = Recursion too deep;
<anonymous> * g_ptr6CA20B54 = &g_t6C952F10;
<anonymous> * g_ptr6CA20B58 = &g_t6C952EF0;
<anonymous> * g_ptr6CA20B5C = &g_t6C952ED0;
Eq_441 g_t6CA20B60 = Recursion too deep;
<anonymous> * g_ptr6CA20B64 = &g_t6C952E50;
<anonymous> * g_ptr6CA20B68 = &g_t6C95A170;
<anonymous> * g_ptr6CA20B6C = &g_t6C952E30;
Eq_441 g_t6CA20B70 = Recursion too deep;
<anonymous> * g_ptr6CA20B74 = &g_t6C952DF0;
<anonymous> * g_ptr6CA20B78 = &g_t6C952DD0;
<anonymous> * g_ptr6CA20B7C = &g_t6C952DB0;
Eq_441 g_t6CA20B80 = Recursion too deep;
<anonymous> * g_ptr6CA20B84 = &g_t6C952D70;
<anonymous> * g_ptr6CA20B88 = &g_t6C952D50;
<anonymous> * g_ptr6CA20B8C = &g_t6C952D30;
Eq_441 g_t6CA20B90 = Recursion too deep;
<anonymous> * g_ptr6CA20B94 = &g_t6C952CE0;
<anonymous> * g_ptr6CA20B98 = &g_t6C952CC0;
<anonymous> * g_ptr6CA20B9C = &g_t6C958F40;
Eq_441 g_t6CA20BA0 = Recursion too deep;
<anonymous> * g_ptr6CA20BA4 = &g_t6C952CA0;
<anonymous> * g_ptr6CA20BA8 = &g_t6C952C80;
<anonymous> * g_ptr6CA20BAC = &g_t6C952C20;
Eq_441 g_t6CA20BB0 = Recursion too deep;
<anonymous> * g_ptr6CA20BB4 = &g_t6C952BE0;
<anonymous> * g_ptr6CA20BB8 = &g_t6C952BC0;
<anonymous> * g_ptr6CA20BBC = &g_t6C952BA0;
Eq_441 g_t6CA20BC0 = Recursion too deep;
<anonymous> * g_ptr6CA20BC4 = &g_t6C952B30;
<anonymous> * g_ptr6CA20BC8 = &g_t6C952AD0;
<anonymous> * g_ptr6CA20BCC = &g_t6C952AA0;
Eq_441 g_t6CA20BD0 = Recursion too deep;
<anonymous> * g_ptr6CA20BD4 = &g_t6C952A50;
<anonymous> * g_ptr6CA20BD8 = &g_t6C952A30;
<anonymous> * g_ptr6CA20BDC = &g_t6C952A00;
Eq_441 g_t6CA20BE0 = Recursion too deep;
<anonymous> * g_ptr6CA20BE4 = &g_t6C952950;
<anonymous> * g_ptr6CA20BE8 = &g_t6C952930;
<anonymous> * g_ptr6CA20BEC = &g_t6C952920;
Eq_441 g_t6CA20BF0 = Recursion too deep;
<anonymous> * g_ptr6CA20BF4 = &g_t6C9528E0;
<anonymous> * g_ptr6CA20BF8 = &g_t6C9528C0;
<anonymous> * g_ptr6CA20BFC = &g_t6C952880;
Eq_441 g_t6CA20C00 = Recursion too deep;
<anonymous> * g_ptr6CA20C04 = &g_t6C952820;
<anonymous> * g_ptr6CA20C08 = &g_t6C9527E0;
<anonymous> * g_ptr6CA20C0C = &g_t6C9527C0;
<anonymous> * g_ptr6CA20C10 = &g_t6C9527A0;
Eq_28 g_t6CA23068 = Recursion too deep;
word32 g_dw6CA2306C = 0x00000002;
ui32 g_dw6CA23070 = 0xBB40E64E;
ui32 g_dw6CA23074 = 0x44BF19B1;
word32 g_dw6CA4A6B0 = 0x6CA1EA81;
char g_str6CA4A6B4[] = "Mingw-w64 runtime failure:\n";
ui32 g_dw6CA4C6EC;
ui32 g_dw6CA4C6F0;
ui32 g_dw6CA4C6F4;
Eq_6442 g_t6CA4C6F8;
int32 g_dw6CA4D000 = 0;
word32 g_dw6CA4F698 = 0x00000000;
word32 g_dw6CA4F9F0 = 0x00000000;
word32 g_dw6CA4F9F4 = 0x00000000;
int32 g_dw6CA4F9F8 = 0;
struct Eq_6248 * g_ptr6CA4F9FC = null;
Eq_106 g_t6CA4FA00 = Recursion too deep;
Eq_28 g_t6CA4FA04 = Recursion too deep;
struct _RTL_CRITICAL_SECTION g_t6CA4FA08 = 
																																																																																																						{
																																																																																																							null,
																																																																																																							0,
																																																																																																							0,
																																																																																																							null,
																																																																																																							null,
																																																																																																							0x00000000,
																																																																																																						};
Eq_106 g_t6CA4FA30 = Recursion too deep;
Eq_106 g_t6CA4FA34 = Recursion too deep;
word32 g_dw6CA4FA38 = 0x00000000;
word32 g_dw6CA4FA3C = 0x00000000;
Eq_101 g_t6CA58000 = Recursion too deep;
Eq_102 g_t6CA58004 = Recursion too deep;
Eq_101 g_t6CA58008 = Recursion too deep;
Eq_102 g_t6CA58010 = Recursion too deep;
<anonymous> * g_a6CA58028[] = 
																																																																																																						{
																																																																																																						};

