// SDL2_text_0006.c
// Generated by decompiling SDL2.dll
// using Reko decompiler version 0.9.1.0.

#include "SDL2_text_0006.h"

// 6C9AC470: void fn6C9AC470(Stack (ptr32 void) ptrArg04, Stack (ptr32 void) ptrArg08, Stack Eq_1909 tArg0C)
void fn6C9AC470(void * ptrArg04, void * ptrArg08, Eq_1909 tArg0C)
{
	memcpy(ptrArg04, ptrArg08, tArg0C);
}

