// SDL2_text_0000.c
// Generated by decompiling SDL2.dll
// using Reko decompiler version 0.9.1.0.

#include "SDL2_text_0000.h"

// 6C94103E: Register up32 fn6C94103E(Register ptr32 ecx, Stack word32 dwArg04, Stack up32 dwArg08, Stack word32 dwArg0C, Register out ptr32 ecxOut)
up32 fn6C94103E(ptr32 ecx, word32 dwArg04, up32 dwArg08, word32 dwArg0C, ptr32 & ecxOut)
{
	up32 eax_15 = dwArg08;
	if (dwArg08 == 0x00)
	{
		int32 edx_114 = globals->dw6CA4D000;
		if (edx_114 <= 0x00)
			goto l6C9411E0;
		globals->dw6CA4D000 = edx_114 - 0x01;
		while (true)
		{
			__lock();
			word32 eax_123;
			__cmpxchg(globals->dw6CA4FA38, 0x01, 0x00, out eax_123);
			union Eq_106 * esp_132 = fp - 0x1C;
			if (eax_123 == 0x00)
				break;
			Sleep(1000);
		}
		if (globals->dw6CA4FA3C != 0x02)
			_amsg_exit(0x1F);
		Eq_106 eax_134 = fn6CA1EAEC();
		if (eax_134 != 0x00)
		{
			Eq_106 ebx_142 = fn6CA1EAEC();
			while (true)
			{
				ptr32 ecx_186;
				ebx_142 -= 0x04;
				if (eax_134 > ebx_142)
					break;
				<anonymous> * eax_176 = *ebx_142;
				if (eax_176 != null)
				{
					word32 edx_184;
					eax_176();
					ecx = ecx_186;
				}
			}
			*esp_132 = (union Eq_106 *) eax_134;
			free(*esp_132);
			&globals->t6CA4FA30.u0->dw0000 = 0x00;
			&globals->t6CA4FA34.u0->dw0000 = 0x00;
		}
		globals->dw6CA4FA3C = 0x00;
		globals->dw6CA4FA38 = 0x00;
	}
	else if (dwArg08 == 0x01)
	{
		word32 ebx_24 = fs->ptr0018->dw0004;
		while (true)
		{
			word32 ebx_33;
			__lock();
			word32 eax_28;
			__cmpxchg(globals->dw6CA4FA38, ebx_24, 0x00, out eax_28);
			if (eax_28 == 0x00)
				break;
			if (ebx_24 == eax_28)
			{
				ebx_33 = 0x01;
				goto l6C941145;
			}
			Sleep(1000);
		}
		ebx_33 = 0x00;
l6C941145:
		if (globals->dw6CA4FA3C == 0x01)
			_amsg_exit(0x1F);
		if (globals->dw6CA4FA3C == 0x00)
		{
			globals->dw6CA4FA3C = 0x01;
			_initterm(&globals->t6CA58008, &globals->t6CA58010);
		}
		if (globals->dw6CA4FA3C == 0x01)
		{
			_initterm(&globals->t6CA58000, &globals->t6CA58004);
			globals->dw6CA4FA3C = 0x02;
		}
		if (ebx_33 == 0x00)
			globals->dw6CA4FA38 = ebx_33;
		if (globals->dw6CA4A6B0 != 0x00)
			ecx = fn6CA1EA81(ecx, dwArg04, dwArg04, 0x02, dwArg0C);
		++globals->dw6CA4D000;
	}
	eax_15 = 0x01;
l6C9411E0:
	ecxOut = ecx;
	return eax_15;
}

// 6C9411E9: Register word32 fn6C9411E9(Register Eq_182 ecx, Register Eq_28 edx, Register out ptr32 ebpOut)
word32 fn6C9411E9(Eq_182 ecx, Eq_28 edx, ptr32 & ebpOut)
{
	word32 edx_134;
	ui32 esi_20 = edx | globals->dw6CA4D000;
	globals->t6CA23068 = edx;
	ptr32 * ebp_188 = fp - 0x04;
	struct Eq_196 * esp_19 = fp - 0x3C;
	if (esi_20 != 0x00)
	{
		up32 ebx_32;
		word32 edi_33;
		word32 esi_34;
		ptr32 ecx_125 = fn6CA1EC63(ecx, ecx, out ebx_32, out ebp_188, out esi_34, out edi_33);
		if (ebx_32 <= 0x02)
		{
			if (fn6C94103E(ecx_125, esi_34, ebx_32, edi_33, out ecx_125) == 0x00)
				goto l6C94131C;
			word32 eax_63 = fn6CA1F600();
			esp_19 = fp - 0x3C;
			if (eax_63 == 0x00)
			{
				if (ebx_32 == 0x01)
				{
					*(ebp_188 - 0x1C) = eax_63;
					word32 ecx_177;
					fn6C94103E(ecx_125, esi_34, 0x00, edi_33, out ecx_177);
					edx_134 = *(ebp_188 - 0x1C);
					goto l6C94131E;
				}
				goto l6C94131C;
			}
			if (ebx_32 == 0x01)
			{
				fn6CA1E91D();
				esp_19 = fp - 0x38;
			}
		}
		esp_19->dw0008 = edi_33;
		esp_19->dw0004 = ebx_32;
		esp_19->dw0000 = esi_34;
		word32 eax_84 = fn6CA1F608();
		ptr32 esp_85 = &esp_19->dw0008 + 0x01;
		edx_134 = eax_84;
		if (ebx_32 == 0x01 && eax_84 == 0x00)
		{
			*(esp_85 - 0x04) = edi_33;
			*(esp_85 - 0x08) = 0x00;
			*(esp_85 - 0x0C) = esi_34;
			fn6CA1F608();
			*(esp_85 - 0x04) = edi_33;
			*(esp_85 - 0x08) = 0x00;
			*(esp_85 - 0x0C) = esi_34;
			fn6CA1F600();
			*(esp_85 - 0x04) = edi_33;
			*(esp_85 - 0x08) = 0x00;
			*(esp_85 - 0x0C) = esi_34;
			word32 ecx_239;
			fn6C94103E(ecx_125, *(esp_85 - 0x0C), *(esp_85 - 0x08), *(esp_85 - 0x04), out ecx_239);
			goto l6C94131C;
		}
		if (ebx_32 != 0x00 && ebx_32 != 0x03)
		{
l6C94131E:
			globals->t6CA23068 = ~0x00;
			ebpOut = *ebp_188;
			return edx_134;
		}
		*(esp_85 - 0x04) = edi_33;
		*(esp_85 - 0x08) = ebx_32;
		*(esp_85 - 0x0C) = esi_34;
		*(ebp_188 - 0x1C) = fn6CA1F600();
		*(esp_85 - 0x04) = edi_33;
		*(esp_85 - 0x08) = ebx_32;
		*(esp_85 - 0x0C) = esi_34;
		word32 ecx_240;
		word32 eax_126 = fn6C94103E(ecx_125, *(esp_85 - 0x0C), *(esp_85 - 0x08), *(esp_85 - 0x04), out ecx_240);
		edx_134 = *(ebp_188 - 0x1C);
		if (eax_126 != 0x00)
			goto l6C94131E;
	}
l6C94131C:
	edx_134 = 0x00;
	goto l6C94131E;
}

// 6C941332: Register Eq_421 DllMain(Stack Eq_422 hModule, Stack Eq_28 dwReason, Stack Eq_182 lpReserved)
Eq_421 DllMain(Eq_422 hModule, Eq_28 dwReason, Eq_182 lpReserved)
{
	globals->dw6CA4F9F0 = 0x00;
	if (dwReason == 0x01)
		fn6CA1E934();
	word32 ebp_26;
	return fn6C9411E9(lpReserved, dwReason, out ebp_26);
}

